### PR TITLE
AsyncTargetWrapper - Do not schedule lazy writer timer, when other active writer

### LINKED ISSUE #3789: AsyncTargetWrapper.ProcessPendingEvents use almost all threads from ThreadPool
**NLog version**: 4.6.7

**Platform**: .NET Framework 4.8

**Current NLog config** (xml or C#, if relevant)

```xml
  <targets async="true">
    <target xsi:type="File"
            name="FatalsOnlyTextLog"
            fileName="${logDirectory}/fatals.txt"
            archiveFileName="${logDirectory}/old/fatals-{#}.zip"
            archiveNumbering="DateAndSequence"
            archiveDateFormat="yyyy-MM-dd"
            archiveEvery="Day"
            archiveAboveSize="5242880"
            maxArchiveFiles="450"
            encoding="UTF-8"
            autoFlush="false"
            layout="${fatalLogMessage}"
            enableArchiveFileCompression="true" />

    <target xsi:type="File"
            name="TextLog"
            fileName="${logDirectory}/log.txt"
            archiveFileName="${logDirectory}/old/log-{#}.zip"
            archiveNumbering="DateAndSequence"
            archiveDateFormat="yyyy-MM-dd"
            archiveEvery="Day"
            archiveAboveSize="5242880"
            maxArchiveFiles="450"
            encoding="UTF-8"
            autoFlush="false"
            layout="${when:when=(level == LogLevel.Fatal or level == LogLevel.Error):inner=${fatalLogMessage}:else=${logMessage}}"
            enableArchiveFileCompression="true"/>

    <target xsi:type="File"
            name="TraceLog"
            fileName="${logDirectory}/trace.txt"
            archiveFileName="${logDirectory}/old/trace-{#}.zip"
            archiveNumbering="DateAndSequence"
            archiveDateFormat="yyyy-MM-dd"
            archiveEvery="Day"
            archiveAboveSize="5242880"
            maxArchiveFiles="450"
            encoding="UTF-8"
            autoFlush="false"
            layout="${when:when=(level == LogLevel.Fatal or level == LogLevel.Error):inner=${fatalLogMessage}:else=${logMessage}}"
            enableArchiveFileCompression="true"/>

    <target xsi:type="ColoredConsole"
            name="ConsoleWriter"
            layout="(${level:uppercase=true})${time}(${threadid}): ${message}${exception:format=tostring:when=(level == LogLevel.Fatal || level == LogLevel.Error)}"
            useDefaultRowHighlightingRules="true">
    </target>
  </targets>
```

- What is the current result?
In very rare cases almost all threads are blocking by method AsyncTargetWrapper.ProcessPendingEvents

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
No, we didn't know about it

- Please post full exception details (message, stacktrace, inner exceptions)
It's very weird bug which we got only twice for 6 months. Application unexpectedly use all threads from ThreadPool. We create dump and found, that most of threads are blocking by AsyncTargetWrapper.ProcessPendingEvents method: 

Dump

If it's important, we have 30-40 log entries per second.

- Are there any workarounds?
No

- Is there a version in which it did work?
I think, no

- Can you help us by writing an unit test?
I don't know how it is possible

### PR DESCRIPTION
**Pull request by snakefoot**
Trying to resolve  #3789. Hard to write an unit-test as it is hard to reproduce (Not even sure it is the issue).

### CODE REVIEW

**Comment by 304NotModified** [comment]
Could we reproduce it locally?

File: src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs [hunk 1]
```diff
@@ -358,27 +358,37 @@ protected virtual void StartLazyWriterTimer()
...
+                                // Not optimal to schedule timer-worker-thread while holding lock,
+                                // as the newly scheduled timer-worker-thread will hammer into the writeLockObject
+                                _lazyWriterTimer.Change(0, Timeout.Infinite);
+                                return true;
+                            }
                         }
                     }
+                    else
+                    {
+                        StartLazyWriterTimer();
```
Comment (304NotModified) [inline src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs]: shouldn't we return `true` here?

**Comment by snakefoot** [comment]
> Could we reproduce it locally?

Not anywhere near the amount that the issue showed.

File: src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs (hunk 1 above)
Comment (snakefoot) [reply src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs]: The return value is whether it successfully scheduled an instant timer, but no harm in returning true here.

**Comment by 304NotModified** [comment]
OK, I think we should merge it as it won't hurt any way? Or do you like to wait for a confirmation?

**Comment by snakefoot** [comment]
I think it should just be merged. Since all evidence was lost (would really have liked to see the internal logger output) and apparently not easy to re-produce.

**Comment by 304NotModified** [comment]
merged 👍  thanks!
