### PR TITLE
MailTarget - Apply Typed Layout for SmtpPort + Timeout

### LINKED ISSUE #3506: Overriding integer proprety with ${appsetting} configuration results in FormatException
Hi,

When trying to use ${appsetting} to override the SMTPPort of MailTarget it throws an exception due to it not being an integer. I'm assuming NLog attempts to store the "${appsetting}" string against the property when it loads the configuration, and then later parses it to its actual value with the layout renderer. I guess this will effect overriding any property that isn't a string regardless of which target it is.

I took a look through the source to try and figure out how to solve it, then figured it wasn't a simple task!

Thanks

**NLog version**: 4.6.5

**Platform**: .Net 4.7.2

**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd" throwExceptions="false" internalLogFile="c:\temp\nlog.log"
	internalLogLevel="Error">

  <variable name="VerboseLayout" value="${threadname}|${longdate}|${level:upperCase=true}|${callsite:includSourcePath=true, methodName=true}|${message}"/>
  <variable name="ExceptionVerboseLayoutEmail"
  	value="${threadname}|${VerboseLayout}${newline}${newline}(${stacktrace:topFrames=10})${newline}${newline}${exception:format=ToString}"/>
  
  <targets async="true">
    <target xsi:type="Mail" name="email" html="false" addNewLines="true" subject="Test" from="nlog@example.com" to="nlog@example.com"
      smtpAuthentication="Basic" enableSsl="false" smtpServer="${appsetting:item=SMTPHost}" smtpUsername="" smtpPassword="" smtpPort="${appsetting:item=SMTPPort}"
      layout="${ExceptionVerboseLayoutEmail}"/>
  </targets>
  <rules>
    <logger name="*" minlevel="Error" writeTo="email"/>
  </rules>
</nlog>

```

- What is the current result? NLog throws an internal exception when trying to use an ${appsetting} against an integer attribute (e.g., SMTP Port) and the target doesn't get added to NLog.LogManager.Configuration. 
- What is the expected result? The mapped AppSetting configuration is allowed and the specifid port is used
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? Yes
- Please post full exception details (message, stacktrace, inner exceptions)
```
2019-07-09 11:14:37.0557 Error Parsing configuration from C:\SourceControl\Applications\Test.Docker\Portal.Test2.Web\NLog.config failed. Exception: NLog.NLogConfigurationException: Exception when parsing C:\SourceControl\Applications\Test.Docker\Portal.Test2.Web\NLog.config.  ---> NLog.NLogConfigurationException: Error when setting property 'SmtpPort' on Mail Target[email] ---> System.Exception: ${appsetting:item=SMTPPort} is not a valid value for Int32. ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.ComponentModel.Int32Converter.FromString(String value, NumberFormatInfo formatInfo)
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   --- End of inner exception stack trace ---
   at System.ComponentModel.BaseNumberConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at NLog.Internal.PropertyHelper.TryTypeConverterConversion(Type type, String value, Object& newValue)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   --- End of inner exception stack trace ---
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
   at NLog.Config.LoggingConfigurationParser.ConfigureObjectFromAttributes(Object targetObject, ILoggingConfigurationElement element, Boolean ignoreType)
   at NLog.Config.LoggingConfigurationParser.ParseTargetElement(Target target, ILoggingConfigurationElement targetElement, Dictionary`2 typeNameToDefaultTargetParameters)
   at NLog.Config.LoggingConfigurationParser.ParseTargetsElement(ILoggingConfigurationElement targetsElement)
   at NLog.Config.LoggingConfigurationParser.ParseNLogSection(ILoggingConfigurationElement configSection)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogSection(ILoggingConfigurationElement configSection)
   at NLog.Config.LoggingConfigurationParser.LoadConfig(ILoggingConfigurationElement nlogConfig, String basePath)
   at NLog.Config.XmlLoggingConfiguration.ParseNLogElement(ILoggingConfigurationElement nlogElement, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.ParseTopLevel(NLogXmlElement content, String filePath, Boolean autoReloadDefault)
   at NLog.Config.XmlLoggingConfiguration.Initialize(XmlReader reader, String fileName, Boolean ignoreErrors)
   --- End of inner exception stack trace ---
```
- Are there any workarounds? I'm guessing I could manually set the port and use LogManager.ReconfigExistingLoggers().
- Is there a version in which it did work? Not that I'm aware of

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #3506

### CODE REVIEW

File: src/NLog/Targets/MailTarget.cs [hunk 1]
```diff
@@ -280,8 +280,7 @@ public Layout Body
         /// Gets or sets the port number that SMTP Server is listening on.
         /// </summary>
         /// <docgen category='SMTP Options' order='15' />
-        [DefaultValue(25)]
```
Comment (304NotModified) [inline src/NLog/Targets/MailTarget.cs:283]: Isn't the defaultValue attribute working now?

**Review by 304NotModified — APPROVED** [review]

File: src/NLog/Targets/MailTarget.cs (hunk 1 above)
Comment (snakefoot) [reply src/NLog/Targets/MailTarget.cs:283]: I was just assuming it didn't work. Will try and use it anyway.

Comment (snakefoot) [reply src/NLog/Targets/MailTarget.cs:283]: Unit tests seems happy, so have added them back. Lets see what the build says. Recall there are some assembly-wide tests that are only executed on the build-server.
