### PR TITLE
UWP with NetStandard2 on Net Native does not support Assembly.CodeBase + Handle native methods in StackTrace

### LINKED ISSUE #2632: Xamarin UWP doesn't create a logfile
**Type** (choose one):
- Bug

**NLog version**: 4.5.0-rc07

**Platform**: .Net 4.7 

**Current NLog config**
```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Trace" internalLogFile="C:\Users\<Path>\nlog-internal.log">
    <targets>
        <target name="file" xsi:type="File"
                layout="${date} | ${level} | ${message}"             
                fileName="${specialfolder:folder=ApplicationData}/qkiss_app-${shortdate}.log"
                keepFileOpen="false"
                encoding="utf-8" />
    </targets>
    <rules>
        <logger name="*" minlevel="Info" writeTo="file" />
    </rules>
</nlog>
```
No log file gets created, even when I use the absolute path for my machine: C:/Users/\<UserName>/AppData/Local/Packages/\<PackageName>/LocalState/\<filePrefix>-${shortdate}.log

What is the current result?  
  - **The logger works fine in debug mode (UWP App)**  
  - Log file won't be created under ReleaseMode. -> .Net Native compilation is on and may couse some 
errors (Reflection etc.)
  - ${environment:USERPROFILE} won't work either

What is the expected result?
  - Creating the log file under ReleaseMode like under DebugMode
 
Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
  - It wasn't created. I did set internalLogLevel=Trace and path for internalLogFile="C:\Users\...\log.log"

Please post full exception details (message, stacktrace, inner exceptions)
  - I don't get an exception. The log file never gets created

Are there any workarounds? 
  - None that I know of

Is there a version in which it did work? 
  - I don't it had ever worked with UWP ReleaseMode

Environment:
- Visual Studio 2017 Version 15.6.4
- .Net Versione 4.7.0.2556
- NetStandard 2.0.1
- NLOG 4.5.0-rc07

### PR DESCRIPTION
**Pull request by snakefoot**
Throws PlatformNotSupportedException when Net Native. Resolves #2632

https://github.com/dotnet/corert/blob/master/src/System.Private.Reflection.Core/src/System/Reflection/Runtime/General/ThunkedApis.cs#L63

And also fixed an issue with GetCurrentClassLogger that returned wrong classname. And also fixed an issue with callsite that threw NullReferenceExceptions. Happy days with Net Native.

### CODE REVIEW

**Comment by 304NotModified** [comment]
I will check, there was a good reason.

**Comment by 304NotModified** [comment]
Related: https://github.com/NLog/NLog/pull/794

**Comment by snakefoot** [comment]
> I will check, there was a good reason.

You don't have to. Think the GAC and unit-test-frameworks are enough reasons not to keep  Assembly.CodeBase. Though one could consider having fallback to Assembly.Location (when Assembly.CodeBase doesn't work), but that is a different PR.

**Comment by 304NotModified** [comment]
There was a fall back, but removed. See #29

**Comment by 304NotModified** [comment]
Any way, we need to check the unc path. Afaik there is no unit test for it.

**Comment by 304NotModified** [comment]
> Could be nice if this callsite/class-lookup logic could extracted to a separate NLog-package, and remove the StackTrace-dependency completely (Ex. for NLog ver. 6).


Don't we need it for every platform?

**Comment by snakefoot** [comment]
> Don't we need it for every platform?

Many people can live without having GetCurrentClassLogger() and Callsite, especially when it means less dependencies and less overhead. Do not recall seeing this logic in Serilog.

**Comment by snakefoot** [comment]
> (Small poll, but better than no poll).

Think those who voted, regret it now as it took 2 years to complete, and everyone was dead in the water :)

>  optional is always nice, but a bit difficult as it's a static method (on logmanager).

Was thinking NLog 6.0 meant breaking old chains. A quick search and replace should be something most programmers are capable of.

**Comment by snakefoot** [comment]
Another thing that should be moved out of NLog is the automatic assembly loading. It has been a pain to maintain, and promiscuous assembly loading is not recommended by security specialists. Instead it should just be an extension to the internal configuration-loader (separate nuget-package).

**Comment by 304NotModified** [comment]
> Any way, we need to check the unc path. Afaik there is no unit test for it.

Could you check if a config from UNC still works, or should I do that?

**Comment by snakefoot** [comment]
> Could you check if a config from UNC still works, or should I do that?

I have not changed anything in the assembly loading, besides handling the PlatformNotSupportedException. But please test away.

File: src/NLog/Config/ConfigurationItemFactory.cs [hunk 1]
```diff
@@ -369,14 +369,11 @@ private static ConfigurationItemFactory BuildDefaultFactory()
                 var extensionDlls = GetNLogExtensionFiles(assemblyLocation);
                 if (extensionDlls.Length==0)
                 {
-                    var entryAssembly = Assembly.GetEntryAssembly();
-                    if (!string.IsNullOrEmpty(entryAssembly?.CodeBase))
+                    var entryLocation = GetAssemblyFileLocation(Assembly.GetEntryAssembly());
+                    if (!string.IsNullOrEmpty(entryLocation) && !string.Equals(entryLocation, assemblyLocation, StringComparison.OrdinalIgnoreCase))
```
Comment (304NotModified) [inline src/NLog/Config/ConfigurationItemFactory.cs]: good check for the `string.Equals` (saves us a `GetNLogExtensionFiles`) 👍

File: src/NLog/Config/ConfigurationItemFactory.cs [hunk 2]
```diff
@@ -473,32 +470,60 @@ private static ConfigurationItemFactory BuildDefaultFactory()
...
+                    InternalLogger.Warn("Skipping auto loading location because location is empty: ({1})", fullName);
+                    return string.Empty;
+                }
+#endif
+
                 Uri assemblyCodeBase;
                 if (!Uri.TryCreate(assembly.CodeBase, UriKind.RelativeOrAbsolute, out assemblyCodeBase))
                 {
-                    InternalLogger.Warn("No auto loading because assembly code base is unknown");
+                    InternalLogger.Warn("Skipping auto loading location because code base is unknown: `{0}` ({1})", assembly.CodeBase, fullName);
```
Comment (304NotModified) [inline src/NLog/Config/ConfigurationItemFactory.cs]: not very important, but why the backticks and not quotes?

File: src/NLog/LoggerImpl.cs [hunk 3]
```diff
@@ -167,12 +167,12 @@ internal static int SkipToUserStackFrameLegacy(StackFrame[] stackFrames, int fir
...
                     continue;
 
-                if (stackFrame.GetMethod().Name == "MoveNext")
+                if (stackFrame.GetMethod()?.Name == "MoveNext")
                 {
                     if (stackFrames.Length > i)
                     {
                         var nextStackFrame = stackFrames[i + 1];
-                        var declaringType = nextStackFrame.GetMethod().DeclaringType;
+                        var declaringType = nextStackFrame.GetMethod()?.DeclaringType;
```
Comment (304NotModified) [inline src/NLog/LoggerImpl.cs]: .GetMethod() cannot return null now, correct?

Comment (snakefoot) [reply src/NLog/LoggerImpl.cs]: Not sure I understand. GetMethod() can return null, so free navigation can be dangerous. See the `stackFrames[i + 1]`.

File: src/NLog/Config/ConfigurationItemFactory.cs (hunk 2 above)
Comment (snakefoot) [reply src/NLog/Config/ConfigurationItemFactory.cs]: Fixed

**Comment by snakefoot** [comment]
> Also small performance improvement, isn't? 

Don't think I have made any performance improvements on purpose. Mostly refactoring to improve the code-reuse for callsite-logic and GetCurrentClassLogger .

File: src/NLog/LoggerImpl.cs (hunk 3 above)
Comment (304NotModified) [reply src/NLog/LoggerImpl.cs]: yes, missed that, thanks!

**Comment by 304NotModified** [comment]
> I have not changed anything in the assembly loading, besides handling the PlatformNotSupportedException. But please test away.

tested it anyway, :) Thanks!

**Comment by snakefoot** [comment]
> @snakefoot I have not changed anything in the assembly loading,

@304NotModified Guess I can withdraw that statement and wait for #2830 to be merged :(
