### PR TITLE
Console Target Automatic Detect if console is available on Mono

### LINKED ISSUE #1704: 4.3.10 Does not log to console under Mono
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

For .NET Core users, please check the platform support: https://github.com/NLog/NLog/wiki/platform-support

**Type** (choose one):
- Bug

**NLog version**: 4.3.10

**Platform**: Mono 4 (Ubuntu 64bit)

In case of a BUG:

- What is the current result? Doesn't log to Console or ColoredConsole
- What is the expected result? Log to console
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)? No
- Please post full exception details (message, stacktrace, inner exceptions): N/A
- Are there any work arrounds? yes/no: Revert to 4.3.9
- Is there a version in which it did worked? 4.3.9
- Can you help us by writing an unit test? N/A?

It worked fine under 4.3.9 and stopped as soon as I updated to 4.3.10. Log files are still being created.

### PR DESCRIPTION
**Pull request by snakefoot**
Extended the console detection check to support Mono, that doesn't support Environment.UserInteractive. Attempt to fix #1704 (Not tested)

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1706)

### CODE REVIEW

**Comment by snakefoot** [comment]
Strange that this build error has started to come:

> ...NLog.UnitTests.Targets.WrappedFileTargetTests.DeleteArchiveFilesByDateWithDateName [FAIL]
   System.IO.IOException : The process cannot access the file 'C:\Users\appveyor\AppData\Local\Temp\1\38d53f98-4243-431f-921b-13c219a6989c\20161012182959914.txt' because it is being used by another process.
   Stack Trace:
      at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
      at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
      at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
      at System.IO.File.Open(String path, FileMode mode)
      C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1307,0): at NLog.Targets.FileTarget.ArchiveFile(String fileName, String archiveFileName)
      C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1579,0): at NLog.Targets.FileTarget.ArchiveByDate(String fileName, String pattern, LogEventInfo logEvent)
      C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1764,0): at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventInfo)
      C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1848,0): at NLog.Targets.FileTarget.TryArchiveFile(String fileName, LogEventInfo ev, Int32 upcomingWriteSize)
      C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1043,0): at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String fileName, Byte[] bytesToWrite)
      C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1136,0): at NLog.Targets.FileTarget.FlushCurrentFileWrites(String currentFileName, LogEventInfo firstLogEvent, MemoryStream ms, List`1 pendingContinuations)
      C:\projects\nlog\src\NLog\Targets\FileTarget.cs(1031,0): at NLog.Targets.FileTarget.Write(AsyncLogEventInfo[] logEvents)
      C:\projects\nlog\src\NLog\Targets\Target.cs(287,0): at NLog.Targets.Target.WriteAsyncLogEvents(AsyncLogEventInfo[] logEvents)
      C:\projects\nlog\tests\NLog.UnitTests\Targets\Mocks\MockTargetWrapper.cs(67,0): at NLog.UnitTests.Targets.Mocks.MockTargetWrapper.Write(AsyncLogEventInfo logEvent)
      C:\projects\nlog\src\NLog\Targets\Target.cs(231,0): at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
      C:\projects\nlog\src\NLog\LoggerImpl.cs(252,0): at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException)
      C:\projects\nlog\src\NLog\LoggerImpl.cs(99,0): at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory)
      C:\projects\nlog\src\NLog\Logger.cs(559,0): at NLog.Logger.WriteToTargets(LogLevel level, IFormatProvider formatProvider, String message)
      C:\projects\nlog\src\NLog\Logger1.cs(454,0): at NLog.Logger.Debug(String message)
      C:\projects\nlog\tests\NLog.UnitTests\Targets\FileTargetTests.cs(890,0): at NLog.UnitTests.Targets.FileTargetTests.DeleteArchiveFilesByDateWithDateName()

File: src/NLog/Targets/ConsoleTargetHelper.cs [hunk 1]
```diff
@@ -41,11 +41,15 @@ internal static class ConsoleTargetHelper
     {
         public static bool IsConsoleAvailable(out string reason)
         {
+            reason = string.Empty;
 #if !SILVERLIGHT && !__IOS__ && !__ANDROID__ && !MONO
             try
             {
                 if (!Environment.UserInteractive)
                 {
+                    if (Type.GetType("Mono.Runtime") != null && Console.In is StreamReader)
```
Comment (304NotModified) [inline src/NLog/Targets/ConsoleTargetHelper.cs]: Maybe we should add this to PlatformDetector and create a unit test for it? (we run on Travis which is Mono)

**Comment by 304NotModified** [comment]
> Strange that this build error has started to come "randomly":

Guess I broke it then in 4.3.10 in #1680

File: src/NLog/Targets/ConsoleTargetHelper.cs [hunk 2]
```diff
@@ -41,11 +41,15 @@ internal static class ConsoleTargetHelper
     {
         public static bool IsConsoleAvailable(out string reason)
         {
+            reason = string.Empty;
 #if !SILVERLIGHT && !__IOS__ && !__ANDROID__ && !MONO
             try
             {
                 if (!Environment.UserInteractive)
                 {
+                    if (Internal.PlatformDetector.IsMono && Console.In is StreamReader)
```
Comment (304NotModified) [inline src/NLog/Targets/ConsoleTargetHelper.cs]: Ps

> 	
I found a way to figure out whether there is a console/terminal available or not under mono on linux: 'Mono.Unix.Native.Syscall.isatty(0)'.

http://stackoverflow.com/questions/9065065/how-to-detect-if-im-running-in-mono-service

Comment (304NotModified) [inline src/NLog/Targets/ConsoleTargetHelper.cs]: :)
