### PR TITLE
LoggingConfiguration - Modify and clone LoggingRules under lock

### LINKED ISSUE #2393: GetTargetsByLevelForLogger - LoggingConfiguration.LoggingRules is not thread safe
```
[xUnit.net 00:00:27.8269283]       System.AggregateException : One or more errors occurred. (Destination array was not long enough. Check the destination index, length, and the array's lower bounds.
[xUnit.net 00:00:27.8270756]       Parameter name: destinationArray)
[xUnit.net 00:00:27.8312139]         ----- Inner Stack Trace -----
[xUnit.net 00:00:27.8312708]            at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
[xUnit.net 00:00:27.8313274]            at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
[xUnit.net 00:00:27.8313899]         /home/travis/build/NLog/NLog/src/NLog/LogFactory.cs(855,0): at NLog.LogFactory.GetTargetsByLevelForLogger(String name, IEnumerable`1 rules, TargetWithFilterChain[] targetsByLevel, TargetWithFilterChain[] lastTargetsByLevel, Boolean[] suppressedLevels)
[xUnit.net 00:00:27.8314531]         /home/travis/build/NLog/NLog/src/NLog/LogFactory.cs(914,0): at NLog.LogFactory.GetConfigurationForLogger(String name, LoggingConfiguration configuration)
[xUnit.net 00:00:27.8315153]         /home/travis/build/NLog/NLog/src/NLog/LogFactory.cs(1218,0): at NLog.LogFactory.GetLogger(LoggerCacheKey cacheKey)
[xUnit.net 00:00:27.8315640]         /home/travis/build/NLog/NLog/tests/NLog.UnitTests/LogManagerTests.cs(572,0): at NLog.UnitTests.LogManagerTests.<>c__DisplayClass25_0.<ThreadSafe_getCurrentClassLogger_test>b__2(Int32 e)
[xUnit.net 00:00:27.8316180]            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
[xUnit.net 00:00:27.8316537]         --- End of stack trace from previous location where exception was thrown ---
```

https://travis-ci.org/NLog/NLog/builds/303097933?utm_source=github_status&utm_medium=notification

### PR DESCRIPTION
**Pull request by snakefoot**
Attempt to resolve #2393 

An extended solution would be to implement a cache of the clone, and mark it dirty whenever LoggingRules are modified. But that is for another day.

The pretty solution would probably be to invent a special thread-safe IList-container, since LoggingRules is also a public property. But that is also for another day.

### CODE REVIEW

**Comment by 304NotModified** [comment]
will try to check this more in-depth this week

File: src/NLog/Config/LoggingConfiguration.cs [hunk 1]
```diff
@@ -104,6 +104,9 @@ public LoggingConfiguration()
         /// </summary>
         public IList<LoggingRule> LoggingRules { get; private set; }
```
Comment (304NotModified) [inline src/NLog/Config/LoggingConfiguration.cs]: I think we could replace this (well the backing field) with `BlockingCollection` when we drop NET35?

File: src/NLog/Config/XmlLoggingConfiguration.cs [hunk 2]
```diff
@@ -779,7 +777,10 @@ private void ParseLoggerElement(NLogXmlElement loggerElement, IList<LoggingRule>
                 }
             }
 
-            rulesCollection.Add(rule);
+            lock (rulesCollection)
+            {
+                rulesCollection.Add(rule);
```
Comment (304NotModified) [inline src/NLog/Config/XmlLoggingConfiguration.cs]: would not expose `AddLoggingRulesSafe` (making it `internal`), a more logical call here? I think i would prefer it (more explit, `CloneLoggingRulesSafe` is alos `internal`)

**Comment by 304NotModified** [comment]
I think this works, expect the ToList for the future. Added some small (rename) proposals

File: src/NLog/Config/LoggingConfiguration.cs (hunk 1 above)
Comment (snakefoot) [reply src/NLog/Config/LoggingConfiguration.cs]: Think it is a little weird to use a producer-consumer collection for a standard IReadOnlyList. But yes another container could be nice.

File: src/NLog/Config/LoggingConfiguration.cs [hunk 3]
```diff
@@ -277,9 +281,10 @@ public void AddRuleForOneLevel(LogLevel level, string targetName, string loggerN
         /// <param name="loggerNamePattern">Logger name pattern. It may include the '*' wildcard at the beginning, at the end or at both ends.</param>
         public void AddRuleForOneLevel(LogLevel level, Target target, string loggerNamePattern = "*")
         {
+            if (target == null) { throw new ArgumentNullException("target"); }
```
[the remark this answers is not in the document]
Comment (snakefoot) [reply src/NLog/Config/LoggingConfiguration.cs]: Fixed

File: src/NLog/Config/LoggingConfiguration.cs [hunk 4]
```diff
@@ -104,6 +104,9 @@ public LoggingConfiguration()
         /// </summary>
         public IList<LoggingRule> LoggingRules { get; private set; }
 
+        internal List<LoggingRule> CloneLoggingRulesSafe() {  lock (LoggingRules) return LoggingRules.ToList(); }
+        private void AddLoggingRulesSafe(LoggingRule rule) { lock (LoggingRules) LoggingRules.Add(rule); }
```
[the remark this answers is not in the document]
Comment (snakefoot) [reply src/NLog/Config/LoggingConfiguration.cs]: Fixed

File: src/NLog/Config/LoggingConfiguration.cs [hunk 5]
```diff
@@ -104,6 +104,9 @@ public LoggingConfiguration()
         /// </summary>
         public IList<LoggingRule> LoggingRules { get; private set; }
 
+        internal List<LoggingRule> CloneLoggingRulesSafe() {  lock (LoggingRules) return LoggingRules.ToList(); }
```
[the remark this answers is not in the document]
Comment (snakefoot) [reply src/NLog/Config/LoggingConfiguration.cs]: Fixed

File: src/NLog/Config/XmlLoggingConfiguration.cs (hunk 2 above)
Comment (snakefoot) [reply src/NLog/Config/XmlLoggingConfiguration.cs]: Not possible for the same method is reused for LoggingRules and ChildRules.

Comment (304NotModified) [reply src/NLog/Config/XmlLoggingConfiguration.cs]: good one, thanks

**Comment by 304NotModified** [comment]
merged, thanks
