### PR TITLE
AutoFlushTargetWrapper - Added FlushOnConditionOnly property

### LINKED ISSUE #3512: Can AutoFlushWrapper be configured to not flush on config reload/shutdown?
**NLog version**: 4.6.5

**Platform**: .NET 4.7.2

**Current NLog config**

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.nlog-project.org/schemas/NLog.xsd NLog.xsd"
      autoReload="true"
      throwExceptions="false"
      internalLogLevel="Off" internalLogFile="c:\temp\nlog-internal.log">

  <targets>
     <target xsi:type="File" name="fileTarget" fileName="log_${cached:${date:format=yyyy-MM-dd HH_mm_ss}}.log" layout="${longdate}|${level:uppercase=true}|${logger}|${message} ${exception:format=ToString,StackTrace}" />		
		
     <target name="crashTraceTarget" xsi:type="AutoFlushWrapper" condition="level >= LogLevel.Fatal">
        <target xsi:type="BufferingWrapper" bufferSize="500" overflowAction="Discard">
           <target xsi:type="File" name="crashTraceFileTarget" fileName="crashtrace_${cached:${date:format=yyyy-MM-dd HH_mm_ss}}.log" layout="${longdate}|${level:uppercase=true}|${logger}|${message} ${exception:format=ToString,StackTrace}" />
        </target>
     </target>
  </targets>

  <rules>
    <logger name="*" minlevel="Info" writeTo="fileTarget" />
    <logger name="*" minlevel="Trace" writeTo="crashTraceTarget" />
  </rules>
</nlog>
```

I'm trying to use `AutoFlushWrapper` to automatically write a log file containing the last 500 `>= Trace` logs when a `Fatal` log is written. This works, however the log file is also flushed on config reload and application exit which is undesirable. Is there a way to set this up so that the `AutoFlushWrapper` does not flush on config reload or application exit, i.e. the buffered logs are discarded on clean exit?

I've had a look at the documentation for custom extensions/wrappers but can't see anything that would allow suppressing the flush on config reload/application exit.

### PR DESCRIPTION
**Pull request by snakefoot**
Skips flush on reload-config and application-shutdown. Resolve #3512 

To be used in combination with BufferingWrapper and `overflowAction=Discard`

### CODE REVIEW

**Comment by snakefoot** [comment]
Notice PR is configured to be merged directly into master!

File: src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs [hunk 1]
```diff
@@ -68,11 +68,18 @@ public class AutoFlushTargetWrapper : WrapperTargetBase
...
+        {
+            get => _asyncFlush ?? true;
             set => _asyncFlush = value;
         }
         private bool? _asyncFlush;
 
+        /// <summary>
+        /// Ignore explicit flush on configuration reload or application shutdown
+        /// </summary>
+        public bool IgnoreExplicitFlush { get; set; }
```
Comment (304NotModified) [inline src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs]: Not sure about this name. I think "explicit" is also a bit difficult here (I think it should be implicit then)

Proposal: FlushOnEvents.

Or, It would be cool if we could split into 2 options, FlushOnShutdown and FlushOnReload, but I expect that's far more difficult to implement?

**Comment by 304NotModified** [comment]
> Notice PR is configured to be merged directly into master!

Thanks! This isn't visible on mobile view. Anyway, I expected it was on master (good choice) :)

File: src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs (hunk 1 above)
Comment (snakefoot) [reply src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs]: Not possible to split into more settings. It will ignore config-reload, application-shutdown and explicit-flush. All of them call the explicit `LogManager.Flush()`

Comment (304NotModified) [reply src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs]: What about, OnlyFlushOnCondition? 

(PS: LogManager.Flush() is explicit, Logmanager.ShutDown is implicit IMO)

Comment (snakefoot) [reply src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs]: To me everything is explicit, except the implicit flush performed by autoflushwrapper.

Comment (snakefoot) [reply src/NLog/Targets/Wrappers/AutoFlushTargetWrapper.cs]: Renamed property to `FlushOnConditionOnly`

**Comment by snakefoot** [comment]
Updated wiki: https://github.com/NLog/NLog/wiki/AutoFlushWrapper-target
