### PR TITLE
${message} renders Exception.GetType + Exception.Message when single exception parameter

### LINKED ISSUE #1034: Incorrect work of option "withException" / logger.Error(ex)
Hi
NLog 4.2.0
It seems that message layout renderer always outputs stack trace if "message" parameter has not been set.

Test code:

``` c#
static void Main(string[] args)
{
    LogManager.GetCurrentClassLogger().Error(new Exception("test 1"));
    LogManager.GetCurrentClassLogger().Error(new Exception("test 2"), string.Empty);
}
```

NLog.config:

``` xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <targets>
        <target xsi:type="File" encoding="UTF-8"
            name="File"
            filename="Log.log"
            layout="${message:withException=true} ${exception:format=tostring}" />
    </targets>

    <rules>
        <logger name="*" minlevel="Trace" writeTo="File" />
    </rules>
</nlog>
```

Result with 'withException=false':

```
System.Exception: test 1 System.Exception: test 1
 System.Exception: test 2
```

Result with 'withException=true':

```
System.Exception: test 1
System.Exception: test 1 System.Exception: test 1

System.Exception: test 2 System.Exception: test 2
```

### LINKED ISSUE #1291: Add special handling for exceptions in Log<T>(...)
NLog should **never** render `${message}` as the return value of `Exception.ToString()`. Instead render `${message}` as the value of `Exception.Message` when no other message is specified by  the caller.

``` c#
catch(Exception e)
{
    // No message was passed -> render ${message} as e.Message instead of e.ToString()
    logger.Error(e);
}
```

Relates to #1290

### PR DESCRIPTION
**Pull request by snakefoot**
Instead of rendering Exception.ToString(). This PR resolves #1034 and resolves #1291 

Users that perform the following logging-operation will no longer get full stacktrace in `${message}`:

`logger.Error(ex);`

Users will still be able to get full stacktrace with `${message:withException=true}` or `${exception}`.

This PR will not affect users that perform the following logger-operation (Maintains the illusion of `string.Format`):

`logger.Error("{0}", ex);`

The new custom formatting is implemented with a special IFormatProvider, that is used when single-parameter-exception. This means `LogEventInfo.FormattedMessage` will also be affected (Will match the output of `${message}`)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Not checked in depth yet, but will ${exception} work with logger.fatal(exception) now? I think that was one of the issues.

File: tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs [hunk 1]
```diff
@@ -219,5 +219,34 @@ public void MessageWithExceptionAndCustomSeparatorTest()
             logger.Debug(ex);
             AssertDebugLastMessage("debug", ex.ToString());
         }
+
+        [Fact]
+        public void SingleParameterException_OutputsSingleStackTrace()
+        {
+            // Stage
```
Comment (304NotModified) [inline tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs]: Please use the term Arrange, -  AAA (Arrange-Act-Assert)

See https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80

File: tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs [hunk 2]
```diff
@@ -219,5 +219,34 @@ public void MessageWithExceptionAndCustomSeparatorTest()
...
+                throw new ArgumentException("Holy Moly");
+            }
+            catch (Exception ex)
+            {
+                logger.Fatal(ex);
+                argException = ex;
+            }
+
+            // Assert
+            Assert.NotNull(argException);
```
Comment (304NotModified) [inline tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs]: this is a strange assert. It asserts not our code. Proposal: remove it

File: tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs [hunk 3]
```diff
@@ -219,5 +219,34 @@ public void MessageWithExceptionAndCustomSeparatorTest()
             logger.Debug(ex);
             AssertDebugLastMessage("debug", ex.ToString());
         }
+
+        [Fact]
+        public void SingleParameterException_OutputsSingleStackTrace()
```
Comment (304NotModified) [inline tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs]: proposal: split the test for ${message} and ${exception}, then its better to read/maintain. 

(please create helpers for duplicate code)

Or use a parameterized test.

File: tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs [hunk 4]
```diff
@@ -219,5 +219,34 @@ public void MessageWithExceptionAndCustomSeparatorTest()
...
+            }
+            catch (Exception ex)
+            {
+                logger.Fatal(ex);
+                argException = ex;
+            }
+
+            // Assert
+            Assert.NotNull(argException);
+            Assert.StartsWith($"{argException.GetType()}: {argException.Message}|{argException.GetType()}", logTarget.LastMessage);
```
Comment (304NotModified) [inline tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs]: Maybe just write out the values? Those are fixed.

So

```
 Assert.StartsWith("System.ArgumentException: Holy Moly |System.ArgumentException", logTarget.LastMessage);
```

**Comment by snakefoot** [comment]
It has been working since NLog 4.5.4


Sent from my Sony Xperia


---- Julian Verdurmen wrote ----


Not checked in depth yet, but will ${exception} work with logger.fatal(exception) now? I think that was one of the issues.

File: tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs (hunk 1 above)
Comment (snakefoot) [reply tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs]: Fixed

File: tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs (hunk 2 above)
Comment (snakefoot) [reply tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs]: Fixed

File: tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs (hunk 3 above)
Comment (snakefoot) [reply tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs]: I prefer the unit-test like this

File: tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs (hunk 4 above)
Comment (snakefoot) [reply tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs]: Fixed

File: tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs (hunk 3 above)
Comment (304NotModified) [reply tests/NLog.UnitTests/LayoutRenderers/MessageTests.cs]: Ok. It's now anyway much better to read :)
