### PR TITLE
Fix wrong warnings on <nlog> element + refactoring

### LINKED ISSUE #3251: "Skipping unknown 'NLog' property" after update to 4.6
Hi,

I have my NLog configs in separate files, normally named nlog.config. When an application starts, i load the config by calling LogManager.LoadConfiguration("nlog.config");

Here's a typical nlog.config:

```
<?xml version="1.0" encoding="utf-8"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" internalLogToConsole="true" internalLogLevel="Warn" autoReload="true"> 
    <!-- Actual configuration -->    
</nlog>
```
After updating to 4.6 i started seeing messages like these in the console upon an application start:

NLog: 2019-03-28 07:32:36.0827 Warn Skipping unknown 'NLog' property internalLogLevel=Warn
NLog: 2019-03-28 07:32:36.1380 Warn Skipping unknown 'NLog' property autoReload=true
NLog: 2019-03-28 07:29:05.0533 Warn Skipping unknown 'NLog' property xmlns=http://www.nlog-project.org/schemas/NLog.xsd
NLog: 2019-03-28 07:29:05.0533 Warn Skipping unknown 'NLog' property xsi=http://www.w3.org/2001/XMLSchema-instance

So, either there was some breaking change in 4.6 which i cannot find any info about or there is a bug. 

Any help is appreciated,
-D

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #3251

### CODE REVIEW

File: src/NLog/Config/LoggingConfigurationParser.cs [hunk 1]
```diff
@@ -132,14 +111,30 @@ protected void LoadConfig(ILoggingConfigurationElement nlogConfig, string basePa
...
         {
-            parseMessageTemplates = null;
-            internalLogFile = null;
+            var dict = CreateNLogConfigDictionary(nlogConfig);
+
+            bool? parseMessageTemplates = null;
+            bool internalLoggerEnabled = false;
             foreach (var configItem in dict)
             {
                 switch (configItem.Key.ToUpperInvariant())
```
Comment (304NotModified) [inline src/NLog/Config/LoggingConfigurationParser.cs]: PS, I don;t think this is needed because of the `StringComparer.OrdinalIgnoreCase` for the dictionary

Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationParser.cs]: It is used for the switch-statement. And also it returns a list, not a dict to promise ordering. Will fix the variable name.

Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationParser.cs]: Fixed the name

**Comment by 304NotModified** [comment]
While I like refactorings, this change is hard to review that no new bugs are introduced. But I you think this is better than #3254, I'm OK with taking this one.

File: src/NLog/Config/LoggingConfigurationParser.cs [hunk 2]
```diff
@@ -184,78 +184,61 @@ private void SetNLogElementSettings(Dictionary<string, string> dict, out bool? p
...
             {
-                if (configItem.Key != null)
+                if (!string.IsNullOrEmpty(configItem.Key))
                 {
                     dict[configItem.Key.Trim()] = configItem.Value;
                 }
             }
 
-            return dict;
+            var sortedDict = new List<KeyValuePair<string, string>>(dict.Count);
```
Comment (304NotModified) [inline src/NLog/Config/LoggingConfigurationParser.cs]: List instead of dict?

File: src/NLog/Config/LoggingConfigurationParser.cs [hunk 3]
```diff
@@ -184,78 +184,61 @@ private void SetNLogElementSettings(Dictionary<string, string> dict, out bool? p
...
+            AddHighPrioritySetting("InternalLogFile", dict, sortedDict);
+            AddHighPrioritySetting("InternalLogToConsole", dict, sortedDict);
+            foreach (var configItem in dict)
+            {
+                sortedDict.Add(configItem);
+            }
+            return sortedDict;
+        }
+
+        private static void AddHighPrioritySetting(string settingName, Dictionary<string, string> dict, List<KeyValuePair<string, string>> sortedDict)
```
Comment (304NotModified) [inline src/NLog/Config/LoggingConfigurationParser.cs]: Could we setup a type that encapsulates the list and dictionary? That type will be responsible for keeping things in sync.

File: src/NLog/Config/LoggingConfigurationParser.cs (hunk 2 above)
Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationParser.cs]: The order is predictable for List, not always for Dictionary.

File: src/NLog/Config/LoggingConfigurationParser.cs (hunk 3 above)
Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationParser.cs]: Not sure I understand the dictionary is temporary and is thrown away. The List is the final result.

File: src/NLog/Config/LoggingConfigurationParser.cs (hunk 2 above)
Comment (304NotModified) [reply src/NLog/Config/LoggingConfigurationParser.cs]: I mean the name of the variable ;)

File: src/NLog/Config/LoggingConfigurationParser.cs (hunk 3 above)
Comment (304NotModified) [reply src/NLog/Config/LoggingConfigurationParser.cs]: Hard to explain. I could refactor it when it's done (as PR)

File: src/NLog/Config/LoggingConfigurationParser.cs (hunk 2 above)
Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationParser.cs]: Fixed

File: src/NLog/Config/LoggingConfigurationParser.cs (hunk 3 above)
Comment (304NotModified) [reply src/NLog/Config/LoggingConfigurationParser.cs]: moved it to an inner method. To encapsulate the AddHighPrioritySetting. That's good enough for now.

(we need some refactor change in the future, as it's strange that we build up a dictionary, change it to list and then use a switch. I think the loop over the switch should be removed and replaced with direct dictionary access (so you can set the ordering easier)

Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationParser.cs]: I read your statement `type that encapsulates the list and dictionary` as creating some weird new container. But yes inner-method helps here, though they ruin readability especially on organic growth beyond 3-4 lines. I guess a better solution would be a Linq-expression or yield that returns IEnumerable.

Comment (304NotModified) [reply src/NLog/Config/LoggingConfigurationParser.cs]: > as creating some weird new container.

True, therefor I also skipped that. 

I think passing parameters to a method which should be in-sync (sorted list - dictionary) is a code smell and I fixed that now with the inner method. Inner methods should be avoided, but for this case it's perfect IMO (or at least, better then the previous situation and the wierd container). 

Another option was to create a new enumerator, but that's overkill for one situation I guess.
