### PR TITLE
XmlLoggingConfiguration - Support ThrowConfigExceptions=true when invalid xml

### LINKED ISSUE #3178: Handle invalid nlog.config / XML better
> When the xml-parser fails to parse the input stream, then NLog should scan the configuration-blob-stream for these strings (without trying to parse as xml):

> throwConfigExceptions="true"
> throwExceptions="true"

this needs probably a regex. Search should be case insensitive and sinqle quote and spaces should also work.

Unit tests are needed for this, TTD recommended

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #3178 and #3025, so it will correctly throw exception when enabled in nlog.config (Even when invalid xml). Have the side effect that it will react to xml-comments that contains throwConfigExceptions=true (or throwExceptions=true), but only when invalid xml.

Unknown NLog-targets will no longer lead to broken NLog-config and nothing logged. Will still fail as expected when throwConfigExceptions=true (or throwExceptions=true)

Notice merge into master. Refactorings extracted from #3521

### CODE REVIEW

File: src/NLog/Config/XmlLoggingConfiguration.cs [hunk 1]
```diff
@@ -77,7 +77,7 @@ public class XmlLoggingConfiguration : LoggingConfigurationParser
         /// Initializes a new instance of the <see cref="XmlLoggingConfiguration" /> class.
         /// </summary>
         /// <param name="fileName">Configuration file to be read.</param>
-        public XmlLoggingConfiguration([CanBeNull] string fileName)
+        public XmlLoggingConfiguration([NotNull] string fileName)
```
Comment (304NotModified) [inline src/NLog/Config/XmlLoggingConfiguration.cs]: looks like a change which is not suitable for a path version? (breaking behavior change)

Comment (snakefoot) [reply src/NLog/Config/XmlLoggingConfiguration.cs]: Well the `[CanBeNull]` is a bug. You cannot load an XmlLoggingConfiguration from a null-filename.

File: src/NLog/Config/LoggingConfigurationParser.cs [hunk 2]
```diff
@@ -1303,15 +1273,29 @@ private static bool ParseBooleanValue(string propertyName, string value, bool de
...
             }
         }
 
+        private bool MustThrowConfigException(NLogConfigurationException configException)
+        {
+            if (configException.MustBeRethrown() || (LogFactory.ThrowConfigExceptions ?? LogFactory.ThrowExceptions))
+                return true;
+
+            if (configException.InnerException != null)
+                InternalLogger.Error(configException.InnerException, configException.Message);
```
[the remark this answers is not in the document]
Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationParser.cs]: Yes you are right. No need to log twice. Have removed the extra-logging.

[the remark this answers is not in the document]
Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationParser.cs]: Like the idea to pass local/active `LoggingConfiguration` / `LogFactory` as parameter to `MustBeRethrown()`. But think that is for NLog 5.0

File: src/NLog/Config/XmlLoggingConfiguration.cs (hunk 1 above)
Comment (304NotModified) [reply src/NLog/Config/XmlLoggingConfiguration.cs]: If we're sure we wont break stuff, I'm happy :) 👍
