### PR TITLE
Layout - Ensure StackTraceUsage works for all types of Layout

### LINKED ISSUE #2044: Sourcefilename and number
**Type** :Question
**NLog version** :4.4.5
**Platform**: .Net 4.0 4.5

Hello together;

Bug or problem ? i dont know

I try to send out into nlogviewer the message + Sourcecodefile and number
thats my konfig for this:
        <target name="Viewer" xsi:type="NLogViewer"
            address="udp4:127.0.0.1:4000"
            includeCallSite="true"
            includeSourceInfo="true"
            includeMdc="true"
            includeNdc="true"
            includeNLogData="true"            
            />            
   
everything works fine but i dont see the Sourcefilename and Linenumber
Thats send to my viewer:

```
<log4j:event` logger="Program" level="TRACE" timestamp="1490959857884" thread="1">
        <log4j:message>
                entering func 'get_Givestring' , Stackframe='22'
        </log4j:message>
        <log4j:locationInfo class="Program.con"
                            method="System.String get_Givestring(System.String)" 
                            file=""
                            line="0"/>
        <log4j:properties>
                <log4j:data name="log4japp" value="Test.exe(12148)"/>
                <log4j:data name="log4jmachinename" value="PC1"/>
        </log4j:properties>
</log4j:event>`
```
thanks for helping 

Klaus

### PR DESCRIPTION
**Pull request by snakefoot**
Fixes #2044 

Little curious whether I'm making a regression of the bug #1262 solved with PR #1310. 

But the difference from that old bug is that now the caching of Layout.StackTraceUsage happens at initialization (single-threaded) instead of at Logger-write (multi-threaded).

This fix has become a very big hammer to a small nail  (Could just have fixed Log4JXmlEventLayout to inherit from IUsesStackTrace). The changes included in this PR:

- Faster allocation of new Loggers, as it now caches the lookup of StackTraceLevel on Target.
- Layout initialization will always scan for StackTraceLevel and ThreadAgnostic. Before it would only scan when initialized with LoggingConfiguration.
- Fixes problem with stale caching of Target.allLayoutsAreThreadAgnostic. Now it is refreshed when calling LogManager.ReconfigExistingLoggers()
  - Same fix is used to refresh the new caching of StackTraceLevel on Target (FindAllLayouts)
- LogManager.ReconfigExistingLoggers() has now become slower as it will now also refresh the caching on all registered Targets (FindAllLayouts)
- LogManager.ReconfigExistingLoggers() is now protected against multiple threads performing re-initialization (will still refresh loggers outside lock)
- Fixes the actual problem with detecting IUsesStackTrace-renders for all Layouts (Also those not depending on SimpleLayout).

### CODE REVIEW

File: src/NLog/Internal/TargetWithFilterChain.cs [hunk 1]
```diff
@@ -97,10 +97,9 @@ internal StackTraceUsage PrecalculateStackTraceUsage()
 
             // find all objects which may need stack trace
             // and determine maximum
-            // only the target can have IUsesStackTrace
             if (Target != null)
             {
-                stackTraceUsage = Target.GetAllLayouts().OfType<IUsesStackTrace>().DefaultIfEmpty().Max(usage => usage == null ? StackTraceUsage.None : usage.StackTraceUsage);
+                stackTraceUsage = Target.GetAllLayouts().DefaultIfEmpty().Max(layout => layout == null ? StackTraceUsage.None : layout.StackTraceUsage);
```
Comment (304NotModified) [inline src/NLog/Internal/TargetWithFilterChain.cs]: maybe it's a good time to move this to `Target.Initialize` ?

File: src/NLog/Layouts/Layout.cs [hunk 2]
```diff
@@ -282,13 +295,26 @@ internal void Initialize(LoggingConfiguration configuration)
...
                 foreach (object item in ObjectGraphScanner.FindReachableObjects<object>(this))
                 {
-                    if (!item.GetType().IsDefined(typeof(ThreadAgnosticAttribute), true))
+                    if (this.threadAgnostic)
                     {
-                        this.threadAgnostic = false;
-                        break;
+                        if (!item.GetType().IsDefined(typeof(ThreadAgnosticAttribute), true))
+                        {
+                            this.threadAgnostic = false;
```
Comment (304NotModified) [inline src/NLog/Layouts/Layout.cs]: I see we lost the `break` here. AFAIK `IsDefined(typeof(ThreadAgnosticAttribute),` not very cheap. 

Maybe we should loop two times (same list) over `ObjectGraphScanner.FindReachableObjects<object>(this)`, and has `breaks` in both loops?

Comment (snakefoot) [inline src/NLog/Layouts/Layout.cs]: Notice the new if-statement above the IsDefined.

Comment (304NotModified) [inline src/NLog/Layouts/Layout.cs]: good one. So not in favor of two loops? It's a bit hard to read.

Comment (snakefoot) [inline src/NLog/Layouts/Layout.cs]: Have now changed it to a Linq-expression.

File: src/NLog/Internal/TargetWithFilterChain.cs (hunk 1 above)
Comment (snakefoot) [inline src/NLog/Internal/TargetWithFilterChain.cs]: Agreed.

**Comment by 304NotModified** [comment]
oops I broke appveyor.yml

**Comment by 304NotModified** [comment]
unbroke it

**Comment by snakefoot** [comment]
@304NotModified Discovered that removing interface from IUsesStackTrace from SimpleLayout, would be a breaking change. Now added it back.

Also discovered that modifying SimpleLayout.Text would automatically refresh the StackTraceUsage. This has also been added back.

NOTE! The caching of StackTraceUsage that you have requested for Target will not be refreshed when creating a new Logger (In case the SimpleLayout-Text has been modified).

**Comment by 304NotModified** [comment]
bitdiffer! I like to add that to that to Appveyor. Do you have the command for it?

File: src/NLog/Layouts/CompoundLayout.cs [hunk 3]
```diff
@@ -64,9 +64,9 @@ public CompoundLayout()
         /// </summary>
         protected override void InitializeLayout()
         {
-            base.InitializeLayout();
             foreach (var layout in Layouts)
                 layout.Initialize(this.LoggingConfiguration);
+            base.InitializeLayout();
```
Comment (304NotModified) [inline src/NLog/Layouts/CompoundLayout.cs]: ow this looks like a breaking behavior change.

**Comment by 304NotModified** [comment]
> NOTE! The caching of StackTraceUsage that you have requested for Target will not be refreshed when creating a new Logger (In case the SimpleLayout-Text has been modified). But the same problem also exists for Target.allLayoutsAreThreadAgnostic

Could you elaborate on this? I'm missing the reference between the Logger and SimpleLayout.

File: src/NLog/Layouts/CompoundLayout.cs (hunk 3 above)
Comment (snakefoot) [inline src/NLog/Layouts/CompoundLayout.cs]: Since the base.InitializeLayout() performs object-scanning, then I wanted it to be last, so it would find all relevant objects. But I will revert the change.

**Comment by snakefoot** [comment]
> Could you please elaborate on this?

When creating a Logger, then it calls LogFactory.GetTargetsByLevelForLogger(). Before this would re-check the StackTraceUsage-status for all Layouts for each Target. When the Target caches the StackTraceUsage, then it will not discover that Layout maybe has been modified.

**Comment by 304NotModified** [comment]
not sure what was wrong on AppVeyor. (build was stuck - 1 hour timeout). Restarted it

**Comment by 304NotModified** [comment]
@snakefoot What do you think? Should this in NLog 4.5 or 4.4.6?

**Comment by snakefoot** [comment]
I would be nice to have this resolved "Fixes problem with stale caching of Target.allLayoutsAreThreadAgnostic" (This bug was introduced with 4.4.2).

The original bug has been there since NLog ver. 4.3, so I don't think it is super urgent. The only issue is that the PR covers several files, so the chance of conflicts is high while waiting for 4.5.

File: src/NLog/Targets/Target.cs [hunk 4]
```diff
@@ -453,18 +451,10 @@ protected virtual void InitializeTarget()
...
-            foreach (Layout layout in this.allLayouts)
-            {
-                if (!layout.IsThreadAgnostic)
-                {
-                    foundNotThreadAgnostic = true;
-                    break;
-                }
-            }
-            this.allLayoutsAreThreadAgnostic = !foundNotThreadAgnostic;
+            this.allLayoutsAreThreadAgnostic = !allLayouts.Any(layout => !layout.ThreadAgnostic);
```
Comment (304NotModified) [inline src/NLog/Targets/Target.cs]: ! Any => .All ? ;)

File: tests/NLog.UnitTests/Layouts/CsvLayoutTests.cs [hunk 5]
```diff
@@ -331,6 +331,7 @@ public void CsvLayoutCachingTest()
                         new CsvColumn("date", "${longdate}"),
                         new CsvColumn("level", "${level}"),
                         new CsvColumn("message", "${message}"),
+                        new CsvColumn("threadid", "${threadid}"),
```
Comment (304NotModified) [inline tests/NLog.UnitTests/Layouts/CsvLayoutTests.cs]: was a new unit test not a better option?

File: src/NLog/Layouts/Layout.cs [hunk 6]
```diff
@@ -271,35 +268,45 @@ void ISupportsInitialize.Close()
...
-		{
+        internal void Initialize(LoggingConfiguration configuration)
+        {
             if (!this.isInitialized)
             {
                 this.LoggingConfiguration = configuration;
                 this.isInitialized = true;
+                this.scannedForObjects = false;
+
+                this.InitializeLayout();
```
Comment (304NotModified) [inline src/NLog/Layouts/Layout.cs]: this is the only thing i'm doubting about. It's now before the scan (yes I see the default scan in InitializeLayout).

I a subclass is dependent of the scan, then we could have problems if it calls base. InitializeLayout() not (or too late)?

File: tests/NLog.UnitTests/Layouts/CsvLayoutTests.cs (hunk 5 above)
Comment (snakefoot) [inline tests/NLog.UnitTests/Layouts/CsvLayoutTests.cs]: Well the unit-test expects the render-result to be cached. And after NLog ver. 4.4.2 then it only caches threadAgnostic = false (Default when not initialized properly)

File: src/NLog/Layouts/Layout.cs (hunk 6 above)
Comment (snakefoot) [inline src/NLog/Layouts/Layout.cs]: For the normalt NLog Layouts, then the scan is purely done for sake of the Target and the later processing of LogEventInfos. Pretty sure no one knows how threadagnostic and stacktraceusage works :)

**Comment by snakefoot** [comment]
> Do you think we have to performance test this one? As it touches all layout and targets?

All the code changes are related to initial configuration, and reload-configuration.

File: src/NLog/Targets/Target.cs (hunk 4 above)
Comment (snakefoot) [inline src/NLog/Targets/Target.cs]: Fixed

**Comment by 304NotModified** [comment]
Thanks for the explanations and code!

**Comment by 304NotModified** [comment]
FYI,

NLog 4.4.6 is live! 

https://www.nuget.org/packages/NLog/4.4.6
