### PR TITLE
TargetWithContext - Easier to capture snapshot of MDLC and NDLC context

### LINKED ISSUE #254: SplitGroup + AsyncWrapper = trouble for thread affinitive or relying on CallContext custom layout renderers
AsyncWrapper breaks CallContext, simply because it transitions to a dedicated thread using a request queue. Totally legitimate, but the CallContext is lost.

Recognizing this, the `AsyncTargetWrapper` class lets the log event to precalculate all the relevant layouts before enqueuing the log event. The precalculated layouts are stored in the layoutCache of the respective log event object. Perfect.

When the final message is rendered (on the dedicated thread) the layout cache is consulted and if the given layout pattern was already precalculated, then the cached value is returned.

The only problem is that the `SimpleLayout` class does not override the `GetHashCode` function. Nor was the dictionary created with a custom equality comparer. 

Thus the caching is broken and it manifests very clearly when there are custom layout renderers relying on the CallContext feature. The log event cache contains the correct layout text, because it was precalculated in the correct CallContext, but then the cache lookup fails and a wrong layout text is rendered and output.

### LINKED ISSUE #2466: Logger could capture MDC and MDLC properties
I can see that many target writers find it very hard to implement support for MDC and MDLC, especially with async-support.

To support async-mode correctly, then the custom target needs help from LayoutRenderers to capture the async-data and convert it into one or more string-objects.

If the custom target wants to generate json, then it can luckily use the JsonLayout that can help with all this, but if this is not the case, then it is hard work.

One could consider extending the LoggingRule (or the Logger-object) with an option that specifies that it should automatically convert MDC and MDLC-properties into standard LogEventInfo.Properties.

Depending on the level of trusted behavior, then one need to be careful with not capturing any random objects, as they might change state until reaching the actual targe-write. This would give some headache for those involved.

Types that can be safely converted from MDC / MDLC into LogEventInfo-Properties:
- Boxed ValueTypes like int, bool, decimal, datetime, etc.
- String-objects.
- Structs that only contains properties of the above type (doing property reflection might get expensive)
- IEnumerable-containers will require deep-clone and will probably give too much overhead.

I'm not sure if these restrictions will make such a feature into another pitfall for the users of MDLC and MDC.

### PR DESCRIPTION
**Pull request by snakefoot**
Attempt to resolve #2466 and #2465

Guess one could also extend it to enable capture of GDC and Callsite.

Maybe implement a helper method than returns all context properties (IncludeAllProperties, IncludeMdlc, IncludeMdc, IncludeGdc).

Suddenly also become a bugfix for correct precalculation of async data for custom NLog-Layouts. Before it would be impossible for custom NLog-Layouts to correctly capture the async-state. Resolves #254

And a bugfix that allows custom NLog-Layouts to work correctly, when they override Layout.Precalculate and are used with Target.OptimizeBufferReuse = true.

### CODE REVIEW

**Comment by snakefoot** [comment]
An alternative approach would be to implement a different async-target-wrapper using ThreadPool.QueueUserWorkItem (or Tasks). Then the async-state will automatically flow with the LogEventInfo (This will not help MDC + NDC but maybe they are also on their way out).

But such async-wrapper will not be able to perform batch-handling, so not that super interesting. And it would also require a special async-buffering-target-wrapper.

**Comment by snakefoot** [comment]
Another thing that could be improved in NLog is the ability to handle batch-writing. Many are able to override the `Write(IList<AsyncLogEventInfo>)`, but then fail to correctly handle:

- Correctly notify if the write-operation succceded or failed by always calling AsyncLogEventInfo.Continuation
- Ensure Max Batch Size so only sending ex. 10 logevents at a time (instead of 100 or 10000 depending on the batch-wrapper).

**Comment by snakefoot** [comment]
@304NotModified Implementing an easier approach for handling batching of log-events, became to messy. But I like this direction for making it easier for custom targets to make use of MDLC and NDLC without forcing them to use JsonLayout.

**Comment by 304NotModified** [comment]
> But I like this direction for making it easier for custom targets to make use of MDLC and NDLC without forcing them to use JsonLayout.

Indeed, that would be a nice improvement! 

Will try to review the PR this weekend.

**Comment by snakefoot** [comment]
Maybe consider to change the default value of the parameter `IncludeMdlc = true`.

File: src/NLog/Internal/ILogMessageFormatter.cs [hunk 1]
```diff
@@ -51,7 +51,7 @@ internal interface ILogMessageFormatter
         /// Has the logevent properties?
         /// </summary>
         /// <param name="logEvent">LogEvent with message to be formatted</param>
-        /// <returns>formatted message</returns>
+        /// <returns>False when logevent has no properties to be extracted</returns>
```
Comment (304NotModified) [inline src/NLog/Internal/ILogMessageFormatter.cs]: good catch :)

File: src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs [hunk 2]
```diff
@@ -43,7 +43,6 @@ namespace NLog.LayoutRenderers.Wrappers
     /// See <a href="http://en.wikipedia.org/wiki/ROT13">http://en.wikipedia.org/wiki/ROT13</a>.
     /// </remarks>
     [LayoutRenderer("rot13")]
-    [AppDomainFixedOutput]
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs]: why is this not needed anymore? I don't see it.

File: src/NLog/Targets/TargetWithContext.cs [hunk 3]
```diff
@@ -0,0 +1,747 @@
...
+                    contextLayout.IncludeNdc = true;
+#if !SILVERLIGHT
+                if (IncludeMdlc && !contextLayout.IncludeMdlc)
+                    contextLayout.IncludeMdlc = true;
+                if (IncludeNdlc && !contextLayout.IncludeNdlc)
+                    contextLayout.IncludeNdlc = true;
+#endif
+                _contextLayout = true;
+            }
+            else if (Layout is JsonLayout jsonLayout)
```
Comment (304NotModified) [inline src/NLog/Targets/TargetWithContext.cs]: I'm not sure if this is good for the maintainability. Could we use/introduce an interface and handle IIncludeContext / JsonLayout  the same? (same for setters). What do you think? 

Maybe we could also check the type of Layout in init?

File: src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs (hunk 2 above)
Comment (snakefoot) [reply src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs]: Thought the attribute meant that the output of the layoutrenderer would be completely static in the life time of the AppDomain (Ex like for newline-layoutrenderer). Cannot see how the same goes for Rot13. Anyway not important for me, so I can re-introduce it, if you want.

File: src/NLog/Targets/TargetWithContext.cs (hunk 3 above)
Comment (snakefoot) [reply src/NLog/Targets/TargetWithContext.cs]: I agree, and have now changed JsonLayout so it implements IIncludeContext.

**Comment by snakefoot** [comment]
@304NotModified Not sure if property-name IncludeSourceInfo is the best (Stolen from Log4JXmlEventLayoutRenderer)

Maybe `IncludeCallSiteWithSource` is easier to understand?

I guess when the CallerMember-attributes becomes part of the official logger interface, then we also need `IncludeCallSiteWithStackTrace`.

**Comment by 304NotModified** [comment]
Oops wrong button ;)

IncludeCallSiteWithSource is indeed much better!

File: src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs (hunk 2 above)
Comment (304NotModified) [reply src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs]: I was thinking it was same output when same input, so independent of other renderers. Need to check that.

**Comment by snakefoot** [comment]
> IncludeCallSiteWithSource is indeed much better!

Done

File: src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs (hunk 2 above)
Comment (304NotModified) [reply src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs]: Checked this, I think ` [AppDomainFixedOutput]` is correct here.  From the code:

a layout(renderer) could be converted to a literal when: 
- The layout and inner layouts are SimpleLayouts, or `[AppDomainFixedOutput]`

So if rot13 has a `SimpleLayout`, it will always have the same output.

**Comment by snakefoot** [comment]
@304NotModified Resolve the merge conflicts, and reverted the rot13 change.

File: src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs (hunk 2 above)
Comment (snakefoot) [reply src/NLog/LayoutRenderers/Wrappers/Rot13LayoutRendererWrapper.cs]: Yes you are right. Actually means that all wrapper layouts should have AppDomainFixedOutput

File: src/NLog/Targets/TargetWithContext.cs [hunk 4]
```diff
@@ -0,0 +1,802 @@
...
+        /// <summary>Internal Layout that allows capture of NDC context</summary>
+        public Layout InternalLayoutNdc { get; }
+#if !SILVERLIGHT
+        /// <summary>Internal Layout that allows capture of MDLC context</summary>
+        public Layout InternalLayoutMdlc { get; }
+        /// <summary>Internal Layout that allows capture of NDLC context</summary>
+        public Layout InternalLayoutNdlc { get; }
+#endif
+        /// <summary>Internal Layout that allows capture of callsite context</summary>
+        public Layout InternalLayoutCallSite { get; }
```
Comment (304NotModified) [inline src/NLog/Targets/TargetWithContext.cs]: I think this is a "trick" for the objectScanner, is that correct?

I'm not sure if exposing those to public (guess it's needed now), is a good idea. I found it confusing and when I subclass this class, it won't understand what to do with those properties.

**Comment by 304NotModified** [comment]
I will release 4.5 RC 4 now,

this could be 4.5 RC5, maybe 4.6 or 5.0

File: src/NLog/Targets/TargetWithContext.cs (hunk 4 above)
Comment (304NotModified) [reply src/NLog/Targets/TargetWithContext.cs]: if so, then my proposal

- make these layouts private
- make a new interface: 

```c#
internal interface IInternalLayouts{ //or maybe public
Layout[] getLayouts(); //or list/or ienumerable
}
```

- implement this interface explicitly (so members are hidden).
- check first for `IInternalLayouts`, combine them with the other found Layouts

File: src/NLog/Targets/TargetWithContext.cs [hunk 5]
```diff
@@ -0,0 +1,802 @@
...
+
+        /// <inheritdoc/>
+        /// <docgen category='General Options' order='10' />
+        bool IncludeEventProperties
+        {
+            get { return _includeEventProperties && !_contextLayout; }
+            set
+            {
+                _includeEventProperties = value;
+                if (Layout is IIncludeContext contextLayout)
```
Comment (304NotModified) [inline src/NLog/Targets/TargetWithContext.cs]: I think it would be nice to always set the contextLayout, but it should be a fake, then create a "fake" impl.

So all the properties just do   `contextLayout.IncludeAllProperties = value;`

File: src/NLog/Targets/TargetWithContext.cs (hunk 4 above)
Comment (snakefoot) [reply src/NLog/Targets/TargetWithContext.cs]: I have found a better trick, that I'm working on now. I will create nested Layouts, where the TopLevel becomes the Target.Layout (And will be scanned). The TopLevel will be similar to CompoundLayout.

Then override the Target.Layout-getter/setter so it will just be a single sub-Layout that lives under the TopLevel-Layout (along with all the context layouts).

Comment (304NotModified) [reply src/NLog/Targets/TargetWithContext.cs]: Smart one!

**Comment by snakefoot** [comment]
@304NotModified Now changed into nested Layouts, so there are no ugly public properties

File: src/NLog/Targets/TargetWithContext.cs [hunk 6]
```diff
@@ -0,0 +1,802 @@
...
+                    contextLayout.IncludeAllProperties = value;
+            }
+        }
+        private bool _includeEventProperties;
+
+        /// <inheritdoc/>
+        /// <docgen category='TargetWithContext Options' order='10' />
+        public bool IncludeGdc
```
[the remark this answers is not in the document]
Comment (snakefoot) [reply src/NLog/Targets/TargetWithContext.cs]: The idea is also to allow the end-user to control what properties to include automatically (using Xml)

**Comment by snakefoot** [comment]
@304NotModified Now removed the automatic forwarding of properties to the inner-layout, think it will be more confusing than helping.

File: src/NLog/Targets/TargetWithContextProperty.cs [hunk 7]
```diff
@@ -0,0 +1,81 @@
...
+        /// Gets or sets the layout that will be rendered as the attribute's value.
+        /// </summary>
+        /// <docgen category='Property Options' order='10' />
+        [RequiredParameter]
+        public Layout Layout { get; set; }
+
+        /// <summary>
+        /// Gets or sets when an empty value should cause the property to be excluded
+        /// </summary>
+        public bool ExcludeEmptyValue { get; set; }
```
Comment (304NotModified) [inline src/NLog/Targets/TargetWithContextProperty.cs]: proposal: change to IncludeEmptyValue (and default = true)

File: src/NLog/Targets/TargetWithContext.cs [hunk 8]
```diff
@@ -0,0 +1,797 @@
...
+
+            return combinedPropties;
+        }
+
+        /// <summary>
+        /// Creates combined dictionary of all configured properties for logEvent
+        /// </summary>
+        /// <param name="logEvent"></param>
+        /// <returns>Dictionary with all collected properties for logEvent</returns>
+        protected IDictionary<string, object> CreateCombinedProperties(LogEventInfo logEvent)
```
Comment (304NotModified) [inline src/NLog/Targets/TargetWithContext.cs]: proposal rename to GetCombinedProperties or maybe even GetAllProperties.

File: src/NLog/Targets/TargetWithContext.cs [hunk 9]
```diff
@@ -0,0 +1,797 @@
...
+        /// </summary>
+        /// <docgen category='Layout Options' order='10' />
+        public bool IncludeCallSiteStackTrace { get => _contextLayout.IncludeCallSiteStackTrace; set => _contextLayout.IncludeCallSiteStackTrace = value; }
+
+        /// <summary>
+        /// Gets the array of custom attributes to be passed into the logevent context
+        /// </summary>
+        /// <docgen category='Layout Options' order='10' />
+        [ArrayParameter(typeof(TargetWithContextProperty), "contextproperty")]
+        virtual public IList<TargetWithContextProperty> ContextProperties { get; }
```
Comment (304NotModified) [inline src/NLog/Targets/TargetWithContext.cs]: isn't strange that we can't set this property ever - and is never set?  Do we mean `abstract` instead of `virtual` here?

File: src/NLog/Targets/TargetWithContext.cs [hunk 10]
```diff
@@ -0,0 +1,797 @@
...
+#endif
+            || (IncludeEventProperties && (logEvent?.HasProperties ?? false));
+        }
+
+        /// <summary>
+        /// Checks if any context properties, and if any returns them as a single dictionary
+        /// </summary>
+        /// <param name="logEvent"></param>
+        /// <returns>Dictionary with any context properties for the logEvent (Null if none found)</returns>
+        protected IDictionary<string, object> LookupContextProperties(LogEventInfo logEvent)
```
Comment (304NotModified) [inline src/NLog/Targets/TargetWithContext.cs]: proposal: rename to GetContextProperties

File: src/NLog/Targets/TargetWithContext.cs [hunk 11]
```diff
@@ -0,0 +1,797 @@
...
+            _contextLayout = _contextLayout ?? new TargetWithContextLayout(this, base.Layout);
+            OptimizeBufferReuse = true;
+        }
+
+        /// <summary>
+        /// Check if logevent has properties (or context properties)
+        /// </summary>
+        /// <param name="logEvent"></param>
+        /// <returns>True if properties should be included</returns>
+        protected bool HasCombinedProperties(LogEventInfo logEvent)
```
Comment (304NotModified) [inline src/NLog/Targets/TargetWithContext.cs]: proposal to rename (after renames below) -> ShouldIncludeProperties

I prefer removing the term "combined properties", if possible

**Comment by 304NotModified** [comment]
oops sorry for breaking the build

File: src/NLog/Targets/TargetWithContext.cs (hunk 9 above)
Comment (snakefoot) [reply src/NLog/Targets/TargetWithContext.cs]: The value is set upfront, so you can just call `ContextProperties.Add`, that is the style from other NLog Targets/Layouts. The `virtual` allows one to provide a different item-class with additional properties.

File: src/NLog/Targets/TargetWithContextProperty.cs [hunk 12]
```diff
@@ -0,0 +1,81 @@
...
+{
+    using NLog.Config;
+    using NLog.Layouts;
+
+    /// <summary>
+    /// Attribute details for <see cref="TargetWithContext"/> 
+    /// </summary>
+    [NLogConfigurationItem]
+    [ThreadAgnostic]
+    public class TargetWithContextProperty
```
[the remark this answers is not in the document]
Comment (snakefoot) [reply src/NLog/Targets/TargetWithContextProperty.cs]: I prefer `TargetWithContext`, since also captures NDC and NDLC

File: src/NLog/Targets/TargetWithContextProperty.cs (hunk 7 above)
Comment (snakefoot) [reply src/NLog/Targets/TargetWithContextProperty.cs]: Done

File: src/NLog/Targets/TargetWithContext.cs (hunk 8 above)
Comment (snakefoot) [reply src/NLog/Targets/TargetWithContext.cs]: Done

File: src/NLog/Targets/TargetWithContext.cs (hunk 10 above)
Comment (snakefoot) [reply src/NLog/Targets/TargetWithContext.cs]: Done

File: src/NLog/Targets/TargetWithContext.cs (hunk 11 above)
Comment (snakefoot) [reply src/NLog/Targets/TargetWithContext.cs]: Done

**Comment by snakefoot** [comment]
> edit: can't see what's wrong. Works locally

There is a conflict with my optimizations of the NetworkTarget and this PR. I have now merged with master, and resolved the conflict.

File: src/NLog/Targets/TargetWithContextProperty.cs (hunk 12 above)
[the remark this answers is not in the document]
Comment (snakefoot) [reply src/NLog/Targets/TargetWithContextProperty.cs]: I prefer `TargetWithContextProperty` since it belongs to `TargetWithContext`. But I'm not religious about the name.

**Comment by 304NotModified** [comment]
merged :)
