### PR TITLE
DatabaseTarget - DbType enum parsing should not be case-sensitive

### LINKED ISSUE #3695: Npgsql Database target parameterType docs are off
**NLog version**: 4.6.8

**Platform**: .NET Core 2.1

**Current NLog config**

```json
{
  "nlog": {
    "autoReload": true,
    "throwExceptions": true,
    "internalLogToConsole": true,
    "internalLogLevel": "Error",
    "variables": {
      "appName": "AbandonedAppEmailAutomation"
    },
    "targets": {
      "Console": {
        "type": "Console",
        "layout": "${level} ${event-properties:EventID:format=tostring} ${callsite:includeSourcePath=false:includeNamespace=false} ${message}",
        "detectConsoleAvailable": false
      },
      "Database": {
        "type": "Database",
        "dbProvider": "Npgsql.NpgsqlConnection, Npgsql",
        "connectionString": "Host=localhost;Database=postgres;Username=postgres;Password=postgres;",
        "commandText": "insert into event (event_type_id, level, exception, system, description, source, callsite, date_created) values (@EventId, @Level, @Exception, @System,  @Description, @Source, @Callsite, CAST(@Date AS timestamp));",
        "parameters": [
          {
            "name": "@System",
            "layout": "${machinename}"
          },
          {
            "name": "@Level",
            "layout": "${level}"
          },
          {
            "name": "@Description",
            "layout": "${message}"
          },
          {
            "name": "@Source",
            "layout": "${appName}"
          },
          {
            "name": "@Callsite",
            "layout": "${callsite}"
          },
          {
            "name": "@EventId",
            "layout": "${event-properties:item=EventId_Id:whenEmpty=6}",
            "dbType": "int64",
            "parameterType": "System.Int64"
          },
          {
            "name": "@Exception",
            "layout": "${exception:format=ToString:innerFormat=ToString}"
          },
          {
            "name": "@Date",
            "layout": "${date:format=yyyy-MM-dd HH\\:mm\\:ss.fff}"
          }
        ]
      }
    },
    "rules": {
      "0": {
        "writeTo": "Console",
        "minlevel": "Info",
        "logger": "*",
        "enabled": true
      },
      "1": {
        "writeTo": "Database",
        "minlevel": "Info",
        "logger": "*",
        "enabled": true 
      }
    }
  }
}
```

- The docs say parameterType should be Int64
- It should actually be System.Int64 like I have specified
- Are there any workarounds? Yes

### PR DESCRIPTION
**Pull request by snakefoot**
Resolves #3695

Cannot figure out why it was ignoreCase=false by default, but have now removed the unused `TryParse`, and instead changed to the public `TryParseEnum`-method that works as intended.

### CODE REVIEW

**Comment by snakefoot** [comment]
Before:
```c#
internal static bool TryParse<TEnum>(string value, out TEnum result) where TEnum : struct
{
   return TryParse(value, false, out result);
}
```
After:
```c#
internal static bool TryParse<TEnum>(string inputValue, out TEnum resultValue) where TEnum : struct
{
   return TryParse(inputValue, true, out resultValue);
}
```
Notice the **true**

**Comment by carlin-q-scott** [comment]
Ah, I only looked at the overload that takes the case sensitive argument. Hopefully the parser code uses the default one.

File: src/NLog/Common/ConversionHelpers.cs [hunk 1]
```diff
@@ -68,30 +68,30 @@ public static class ConversionHelpers
...
+        /// <param name="inputValue">The string representation of the enumeration name or underlying value to convert.</param>
+        /// <param name="resultValue">When this method returns, result contains an object of type TEnum whose value is represented by value if the parse operation succeeds. If the parse operation fails, result contains the default value of the underlying type of TEnum. Note that this value need not be a member of the TEnum enumeration. This parameter is passed uninitialized.</param>
         /// <returns><c>true</c> if the value parameter was converted successfully; otherwise, <c>false</c>.</returns>
         /// <remarks>Wrapper because Enum.TryParse is not present in .net 3.5</remarks>
-        internal static bool TryParse<TEnum>(string value, out TEnum result) where TEnum : struct
+        internal static bool TryParse<TEnum>(string inputValue, out TEnum resultValue) where TEnum : struct
```
Comment (304NotModified) [inline src/NLog/Common/ConversionHelpers.cs]: What about input and result?

File: src/NLog/Common/ConversionHelpers.cs [hunk 2]
```diff
@@ -68,30 +68,30 @@ public static class ConversionHelpers
...
         {
-            return TryParse(value, false, out result);
+            return TryParse(inputValue, true, out resultValue);
```
Comment (304NotModified) [inline src/NLog/Common/ConversionHelpers.cs]: This is a bit unexpected, changing the default for the whole code?

File: src/NLog/Common/ConversionHelpers.cs [hunk 3]
```diff
@@ -68,30 +68,30 @@ public static class ConversionHelpers
         /// Converts the string representation of the name or numeric value of one or more enumerated constants to an equivalent enumerated object. A parameter specifies whether the operation is case-sensitive. The return value indicates whether the conversion succeeded.
```
Comment (304NotModified) [inline src/NLog/Common/ConversionHelpers.cs]: Guess we need to update these docs? 

> A parameter specifies whether the operation is case-sensitive

File: src/NLog/Common/ConversionHelpers.cs (hunk 2 above)
Comment (304NotModified) [reply src/NLog/Common/ConversionHelpers.cs]: (I missed the intro text, oops)

Comment (304NotModified) [reply src/NLog/Common/ConversionHelpers.cs]: Enum.TryParse (.net 4+) is case sensitive by default?

File: src/NLog/Common/ConversionHelpers.cs (hunk 1 above)
Comment (snakefoot) [reply src/NLog/Common/ConversionHelpers.cs]: Just aligning with the public method,.

File: src/NLog/Common/ConversionHelpers.cs (hunk 2 above)
Comment (snakefoot) [reply src/NLog/Common/ConversionHelpers.cs]: Well when parsing then one wants to be case-insensitive, unless knowing the writer is strict. So ignoreCase=true is a better default for NLog. Just like for the public method

File: src/NLog/Common/ConversionHelpers.cs (hunk 3 above)
Comment (snakefoot) [reply src/NLog/Common/ConversionHelpers.cs]: Updated

**Comment by snakefoot** [comment]
After putting on my thinking hat, then I have decided to completely remove the internal TryParse-method without ignoreCase-parameter. Instead changed to the public `TryParseEnum`-method. This will also make it easier to rip out DatabaseTarget from NLog-core in NLog 5.0.

**Comment by 304NotModified** [comment]
Good choice!

File: src/NLog/Common/ConversionHelpers.cs [hunk 4]
```diff
@@ -42,7 +42,7 @@ namespace NLog.Common
     public static class ConversionHelpers
     {
         /// <summary>
-        /// Converts input string value into <see cref="System.Enum"/>
+        /// Converts input string value into <see cref="System.Enum"/>. Parsing is case-insensitive.
```
Comment (304NotModified) [inline src/NLog/Common/ConversionHelpers.cs]: This is wrong now?

File: src/NLog/Common/ConversionHelpers.cs [hunk 5]
```diff
@@ -68,30 +68,17 @@ public static class ConversionHelpers
...
+        /// <param name="resultValue">When this method returns, result contains an object of type TEnum whose value is represented by value if the parse operation succeeds. If the parse operation fails, result contains the default value of the underlying type of TEnum. Note that this value need not be a member of the TEnum enumeration. This parameter is passed uninitialized.</param>
         /// <returns><c>true</c> if the value parameter was converted successfully; otherwise, <c>false</c>.</returns>
         /// <remarks>Wrapper because Enum.TryParse is not present in .net 3.5</remarks>
-        internal static bool TryParse<TEnum>(string value, bool ignoreCase, out TEnum result) where TEnum : struct
+        internal static bool TryParse<TEnum>(string inputValue, bool ignoreCase, out TEnum resultValue) where TEnum : struct
```
Comment (304NotModified) [inline src/NLog/Common/ConversionHelpers.cs]: I can't comment on the original comment, (due to force push),

But IMO inputValue and resultValue is double and more confusing than helping.  Note, the orignal method has following signature:

```
public static bool TryParse<TEnum> (string value, bool ignoreCase, out TEnum result) where TEnum : struct;
```

I don't know where it's aligned with now in this PR? Currently I still prefer the way before

File: src/NLog/Common/ConversionHelpers.cs (hunk 4 above)
Comment (snakefoot) [reply src/NLog/Common/ConversionHelpers.cs]: Not sure I understand. Thought you wanted me to update documentation to match actual behavior.

File: src/NLog/Common/ConversionHelpers.cs (hunk 5 above)
Comment (snakefoot) [reply src/NLog/Common/ConversionHelpers.cs]: No problem. Will revert this change. Just wanted to align with the method you introduced yourself TryParseEnum. But I see now this was a mistake.

File: src/NLog/Common/ConversionHelpers.cs (hunk 4 above)
Comment (304NotModified) [reply src/NLog/Common/ConversionHelpers.cs]: I'm confused I guess

>  I have decided to completely remove the internal TryParse-method without ignoreCase-parameter

So there is a still a tryparse without ignoreCase?

(and if we have the ignoreCase parameter, "Parsing is case-insensitive." is wrong)

PS: the diff made it here conflusing

Comment (snakefoot) [reply src/NLog/Common/ConversionHelpers.cs]: Nope. Your existing public method `TryParseEnum` was case-insensitive already (see the source code). When I implemented parsing of DbType-enum I used an internal method TryParse that was case-sensitive. I have now removed this internal method TryParse, and now using public method `TryParseEnum` (Just like I wrote about putting on my thinking hat).

Comment (304NotModified) [reply src/NLog/Common/ConversionHelpers.cs]: Ok thank for the clarification!
