### PR TITLE
Fix LayoutParser should throw ConfigExceptions on unknown properties

### LINKED ISSUE #3996: LayoutParser should throw ThrowConfigExceptions on unknown properties
Change so it throws `NLogConfigurationException` when `ThrowConfigExceptions = true`

https://github.com/NLog/NLog/blob/733ce6e65045fd93de8bad6f9c5c67639e2d0978/src/NLog/Layouts/LayoutParser.cs#L384-L385

https://github.com/NLog/NLog/blob/733ce6e65045fd93de8bad6f9c5c67639e2d0978/src/NLog/Layouts/LayoutParser.cs#L436

https://github.com/NLog/NLog/blob/733ce6e65045fd93de8bad6f9c5c67639e2d0978/src/NLog/Layouts/LayoutParser.cs#L455-L456

### PR DESCRIPTION
**Pull request by njqdev**
Fixes #3996 

I added a test for https://github.com/NLog/NLog/blob/733ce6e65045fd93de8bad6f9c5c67639e2d0978/src/NLog/Layouts/LayoutParser.cs#L384-L385 

And another for https://github.com/NLog/NLog/blob/733ce6e65045fd93de8bad6f9c5c67639e2d0978/src/NLog/Layouts/LayoutParser.cs#L455-L456

### CODE REVIEW

File: src/NLog/Layouts/LayoutParser.cs [hunk 1]
```diff
@@ -386,7 +386,10 @@ private static LayoutRenderer ParseLayoutRenderer(ConfigurationItemFactory confi
                         var value = ParseParameterValue(stringReader);
                         if (!string.IsNullOrEmpty(parameterName) || !StringHelpers.IsNullOrWhiteSpace(value))
                         {
-                            // TODO NLog 5.0 Should throw exception when invalid configuration (Check throwConfigExceptions)
+                            if (throwConfigExceptions ?? LogManager.ThrowConfigExceptions == true)
```
Comment (snakefoot) [inline src/NLog/Layouts/LayoutParser.cs:389]: Why not: `if (throwConfigExceptions ?? LogManager.ThrowConfigExceptions ?? LogManager.ThrowExceptions)` ?

File: src/NLog/Layouts/LayoutParser.cs [hunk 2]
```diff
@@ -457,7 +460,10 @@ private static void SetDefaultPropertyValue(ConfigurationItemFactory configurati
             }
             else
             {
-                // TODO NLog 5.0 Should throw exception when invalid configuration (Check throwConfigExceptions)
+                if (throwConfigExceptions ?? LogManager.ThrowConfigExceptions == true)
```
Comment (snakefoot) [inline src/NLog/Layouts/LayoutParser.cs:463]: Why not: `if (throwConfigExceptions ?? LogManager.ThrowConfigExceptions ?? LogManager.ThrowExceptions)` ?

File: src/NLog/Layouts/LayoutParser.cs [hunk 3]
```diff
@@ -386,7 +386,10 @@ private static LayoutRenderer ParseLayoutRenderer(ConfigurationItemFactory confi
                         var value = ParseParameterValue(stringReader);
                         if (!string.IsNullOrEmpty(parameterName) || !StringHelpers.IsNullOrWhiteSpace(value))
                         {
-                            // TODO NLog 5.0 Should throw exception when invalid configuration (Check throwConfigExceptions)
+                            if (throwConfigExceptions ?? LogManager.ThrowConfigExceptions == true)
+                            {
+                                throw new NLogConfigurationException("Unrecognized property '{0}={1}` for ${{{2}}} ({3})", parameterName, value, name, layoutRenderer?.GetType());
```
Comment (snakefoot) [inline src/NLog/Layouts/LayoutParser.cs:391]: Instead of having the same log formatting twice, then one could consider this:

```c#
var configException = new NLogConfigurationException("Unrecognized property '{0}={1}` for ${{{2}}} ({3})", parameterName, value, name, layoutRenderer?.GetType());
if (throwConfigExceptions ?? LogManager.ThrowConfigExceptions ?? LogManager.ThrowExceptions)
     throw configException;

InternalLogger.Warn(configException.Message);
```

File: src/NLog/Layouts/LayoutParser.cs [hunk 4]
```diff
@@ -438,7 +441,7 @@ private static LayoutRenderer GetLayoutRenderer(ConfigurationItemFactory configu
             {
                 if (throwConfigExceptions ?? LogManager.ThrowConfigExceptions ?? LogManager.ThrowExceptions)
                 {
-                    throw;  // TODO NLog 5.0 throw NLogConfigurationException. Maybe also include entire input layout-string (if not too long)
+                    throw new NLogConfigurationException("Error parsing layout {0}", name);
```
Comment (snakefoot) [inline src/NLog/Layouts/LayoutParser.cs:444]: Instead of having the same log formatting twice, then one could consider this:

```c#
var configException = new NLogConfigurationException(ex, $"Error parsing layout {name}");
if (throwConfigExceptions ?? LogManager.ThrowConfigExceptions ?? LogManager.ThrowExceptions)
     throw configException;

InternalLogger.Warn(ex, configException.Message);
```

File: src/NLog/Layouts/LayoutParser.cs [hunk 5]
```diff
@@ -457,7 +460,10 @@ private static void SetDefaultPropertyValue(ConfigurationItemFactory configurati
             }
             else
             {
-                // TODO NLog 5.0 Should throw exception when invalid configuration (Check throwConfigExceptions)
+                if (throwConfigExceptions ?? LogManager.ThrowConfigExceptions == true)
+                {
+                    throw new NLogConfigurationException("{0} has no default property to assign value {1}", layoutRenderer.GetType(), value);
```
Comment (snakefoot) [inline src/NLog/Layouts/LayoutParser.cs:465]: Instead of having the same log formatting twice, then one could consider this:

```c#
var configException = new NLogConfigurationException($"{layoutRenderer.GetType()} has no default property to assign value {value}");
if (throwConfigExceptions ?? LogManager.ThrowConfigExceptions ?? LogManager.ThrowExceptions)
     throw configException;

InternalLogger.Warn(configException.Message);
```

File: src/NLog/Layouts/LayoutParser.cs (hunk 2 above)
Comment (njqdev) [reply src/NLog/Layouts/LayoutParser.cs:463]: This causes the test below to fail

https://github.com/NLog/NLog/blob/dev/tests/NLog.UnitTests/LayoutRenderers/Wrappers/WhenEmptyTests.cs#L72

File: src/NLog/Layouts/LayoutParser.cs (hunk 3 above)
Comment (njqdev) [reply src/NLog/Layouts/LayoutParser.cs:391]: This makes `WhenEmpty_MissingInner_ShouldNotThrow` fail as well.

File: src/NLog/Layouts/LayoutParser.cs (hunk 4 above)
Comment (njqdev) [reply src/NLog/Layouts/LayoutParser.cs:444]: Is it really a rethrow in this case? I thought it should only be used like this:

https://github.com/NLog/NLog/blob/dev/src/NLog/Internal/AssemblyHelpers.cs#L176-L180

File: src/NLog/Layouts/LayoutParser.cs (hunk 5 above)
Comment (njqdev) [reply src/NLog/Layouts/LayoutParser.cs:465]: Here it's not a rethrow unless I'm mistaken about something. Also, if the `InternalLogger.Warn` is removed then nothing will be logged at all if throwing isn't enabled right?

```c#
var configException = new NLogConfigurationException($"{layoutRenderer.GetType()} has no default property to assign value {value}");
if (throwConfigExceptions ?? configException.MustBeRethrown())
     throw configException;
InternalLogger.Warn("{0} has no default property to assign value {1}", layoutRenderer.GetType(), value);
```

File: src/NLog/Layouts/LayoutParser.cs (hunk 2 above)
Comment (snakefoot) [reply src/NLog/Layouts/LayoutParser.cs:463]: Can you show why it fails? I'm guessing that it should test that `${environment:LOG_DIR_XXX}` should not fail when `LOG_DIR_XXX` does not it exists.

File: src/NLog/Layouts/LayoutParser.cs (hunk 3 above)
Comment (snakefoot) [reply src/NLog/Layouts/LayoutParser.cs:391]: Can you show why it fails?

File: src/NLog/Layouts/LayoutParser.cs (hunk 4 above)
Comment (snakefoot) [reply src/NLog/Layouts/LayoutParser.cs:444]: It can also be used like this: https://github.com/NLog/NLog/blob/6198b8696c1bf571e2266c599063557fe486dcc6/src/NLog/Config/LoggingConfigurationElementExtensions.cs#L108

File: src/NLog/Layouts/LayoutParser.cs (hunk 5 above)
Comment (snakefoot) [reply src/NLog/Layouts/LayoutParser.cs:465]: @njqdev The `MustBeRethrown()`-extension-method will perform logging to the InternalLogger.

File: src/NLog/Layouts/LayoutParser.cs (hunk 2 above)
Comment (njqdev) [reply src/NLog/Layouts/LayoutParser.cs:463]: Maybe something is wrong with the literal? The test passes if I remove the value of `text` like below:

```c#
SimpleLayout l = @"${whenEmpty:whenEmpty=${literal:text=}:inner=${environment:LOG_DIR_XXX}}api.log";
```

Stack traces when adding `?? LogManager.ThrowExceptions` here or in the other method:
```
Message: 
    NLog.NLogConfigurationException : NLog.LayoutRenderers.LiteralLayoutRenderer has no default property to assign value logs}
Stack Trace: 
    LayoutParser.SetDefaultPropertyValue(ConfigurationItemFactory configurationItemFactory, LayoutRenderer layoutRenderer, String value, Nullable`1 throwConfigExceptions) line 465
    LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader, Nullable`1 throwConfigExceptions) line 419
    LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Nullable`1 throwConfigExceptions, Boolean isNested, String& text) line 104
    LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader, Nullable`1 throwConfigExceptions) line 400
    LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Nullable`1 throwConfigExceptions, Boolean isNested, String& text) line 104
    SimpleLayout.SetLayoutText(String value, Nullable`1 throwConfigExceptions) line 137
```

```
Message: 
    NLog.NLogConfigurationException : Unrecognized property 'inner=${environment` for ${literal} (NLog.LayoutRenderers.LiteralLayoutRenderer)
  Stack Trace: 
    LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader, Nullable`1 throwConfigExceptions) line 391
    LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Nullable`1 throwConfigExceptions, Boolean isNested, String& text) line 104
    LayoutParser.ParseLayoutRenderer(ConfigurationItemFactory configurationItemFactory, SimpleStringReader stringReader, Nullable`1 throwConfigExceptions) line 400
    LayoutParser.CompileLayout(ConfigurationItemFactory configurationItemFactory, SimpleStringReader sr, Nullable`1 throwConfigExceptions, Boolean isNested, String& text) line 104
    SimpleLayout.SetLayoutText(String value, Nullable`1 throwConfigExceptions) line 137
```

Comment (snakefoot) [reply src/NLog/Layouts/LayoutParser.cs:463]: Seems that `${literal:text=}` has special powers that affects normal parsing. It seems it tries to swallow more than expected since it reaches `inner=${environment`.  See also https://github.com/NLog/NLog/wiki/Literal-Layout-Renderer  Maybe there is a unwanted feature when handling parsing of `${literal}`.

Comment (snakefoot) [reply src/NLog/Layouts/LayoutParser.cs:463]: @njqdev If you feel that crawling around in the LayoutRenderer-parser-dungeon is a bit too much, then please tell. It was a little unexpected that dragons should be lurking here.

Comment (njqdev) [reply src/NLog/Layouts/LayoutParser.cs:463]: Sure, I can investigate it and get back to you later.

Comment (njqdev) [reply src/NLog/Layouts/LayoutParser.cs:463]: @snakefoot it's a test for when `WrapperLayoutRendererBase.Inner` is null. Here's a memory refresher: https://github.com/NLog/NLog/pull/2908

The text not being escaped in `literal:text=c:\logs\` is what caused it to throw after my changes, see #2844. So the test was passing before because of the parsing failing, config exceptions not being thrown and a layout renderer with a null Inner being created.

I could change the test to the below, which results in a null Inner and the test passing. Or change `LogManager.ThrowExceptions` to false in the test, if that makes sense. What do you think?

```c#
        [Fact]
        public void WhenEmpty_MissingInner_ShouldNotThrow()
        {
            LogManager.ThrowExceptions = true;
            SimpleLayout l = @"${whenEmpty:whenEmpty=${literal:text=c\:\\logs\\}}api.log";
            var le = LogEventInfo.Create(LogLevel.Info, "logger", "message");
            Assert.Equal("api.log", l.Render(le));
        }
```

Comment (snakefoot) [reply src/NLog/Layouts/LayoutParser.cs:463]: Thank you for the reminder. So the unit-test was created to show that it would not explode when `Inner = null` because of faulty escaping in `${literal:text=c:\logs\}`. So actually this PR will correctly reject this faulty escaping (which is good), but then it will fail to validate that `Inner == null` will not cause issues. Maybe change the unit-test into this:

```c#
        [Fact]
        public void WhenEmpty_MissingInner_ShouldNotThrow()
        {
          using (new NoThrowNLogExceptions())
          {
              SimpleLayout l = @"${whenEmpty:whenEmpty=${literal:text=c\:\\logs\\}}api.log";
              var le = LogEventInfo.Create(LogLevel.Info, "logger", "message");
              LogManager.ThrowExceptions = true;
              Assert.Equal("api.log", l.Render(le)); // Assert that missing Inner-property will not throw
          }
        }
```

Comment (snakefoot) [reply src/NLog/Layouts/LayoutParser.cs]: @njqdev Sorry was a little too quick with my suggetion. Have updated my code-suggestion above, so the LayoutParser will continue to fail, so `Inner`-property remains `null`.

File: src/NLog/Layouts/LayoutParser.cs [hunk 6]
```diff
@@ -386,7 +386,10 @@ private static LayoutRenderer ParseLayoutRenderer(ConfigurationItemFactory confi
                         var value = ParseParameterValue(stringReader);
                         if (!string.IsNullOrEmpty(parameterName) || !StringHelpers.IsNullOrWhiteSpace(value))
                         {
-                            // TODO NLog 5.0 Should throw exception when invalid configuration (Check throwConfigExceptions)
+                            if (throwConfigExceptions ?? LogManager.ThrowConfigExceptions ?? LogManager.ThrowExceptions)
```
Comment (snakefoot) [inline src/NLog/Layouts/LayoutParser.cs:389]: Should also use:

```c#
var configException = new NLogConfigurationException($"Unrecognized property '{parameterName}={value}` for ${{{name}}} ({layoutRenderer?.GetType()})");
if (throwConfigExceptions ?? configException.MustBeRethrown())
     throw configException;
```

File: src/NLog/Layouts/LayoutParser.cs [hunk 7]
```diff
@@ -457,8 +461,12 @@ private static void SetDefaultPropertyValue(ConfigurationItemFactory configurati
...
             else
             {
-                // TODO NLog 5.0 Should throw exception when invalid configuration (Check throwConfigExceptions)
-                InternalLogger.Warn("{0} has no default property to assign value {1}", layoutRenderer.GetType(), value);
+                var configException = new NLogConfigurationException($"{layoutRenderer.GetType()} has no default property to assign value {value}");
+                if (throwConfigExceptions ?? configException.MustBeRethrown())
+                {
+                    throw configException;
+                }
+                InternalLogger.Warn(configException.Message);
```
Comment (snakefoot) [inline src/NLog/Layouts/LayoutParser.cs:469]: `InternalLogger.Warn(configException.Message);` is not necessary, since `configException.MustBeRethrown()` will perform logging.

File: tests/NLog.UnitTests/LayoutRenderers/Wrappers/WhenEmptyTests.cs [hunk 8]
```diff
@@ -71,10 +71,13 @@ public void CoalesceWithANestedLayout()
         [Fact]
         public void WhenEmpty_MissingInner_ShouldNotThrow()
         {
-            LogManager.ThrowExceptions = true;
-            SimpleLayout l = @"${whenEmpty:whenEmpty=${literal:text=c:\logs\}:inner=${environment:LOG_DIR_XXX}}api.log";
-            var le = LogEventInfo.Create(LogLevel.Info, "logger", "message");
-            Assert.Equal("api.log", l.Render(le));
+            using (new NoThrowNLogExceptions())
+            {
+                SimpleLayout l = @"${whenEmpty:whenEmpty=${literal:text=c\:\\logs\\}}api.log";
```
Comment (snakefoot) [inline tests/NLog.UnitTests/LayoutRenderers/Wrappers/WhenEmptyTests.cs:76]: Should remain `SimpleLayout l = @"${whenEmpty:whenEmpty=${literal:text=c:\logs\}:inner=${environment:LOG_DIR_XXX}}api.log";` (To ensure Inner becomes `null`)

**Comment by snakefoot** [comment]
It looks great. Only have 3 small nitpicks, and then I think it is ready to merge. Thank you for the hard work.

File: src/NLog/Layouts/LayoutParser.cs (hunk 6 above)
Comment (njqdev) [reply src/NLog/Layouts/LayoutParser.cs:389]: Alright. I didn't change it since the messages differed: `Skipping unrecognized property`

Comment (snakefoot) [reply src/NLog/Layouts/LayoutParser.cs:389]: Maybe just repeat the trick you did here:

`InternalLogger.Error(ex, "{0} will be ignored.", configException.Message);`

**Comment by snakefoot** [comment]
Closing and re-opening pull-request to tickle the build-servers.

**Review by snakefoot — APPROVED** [review]
Looks great and with 100 pct code-coverage.

**Comment by 304NotModified** [comment]
Thanks!
