### PR TITLE
Log4JXmlEventLayout - Fixed bug with empty nlog:properties & added IncludeAllProperties option

### LINKED ISSUE #2088: Log4JXmlEventLayout exports a <nlog:properties /> tag
Hello,

So, I have nlog 4.4.8 installed, and I am using this target in my app.config:

`<target name="logFile" xsi:type="File" fileName="${logDirectory}/log.xml" archiveFileName="${logDirectory}/log.${shortdate}.{#####}.xml" archiveNumbering="Sequence" archiveEvery="Day" archiveAboveSize="10240000" keepFileOpen="false" maxArchiveFiles="1000">
        <layout xsi:type="Log4JXmlEventLayout" />
      </target>`

What happens (with the 4.4.8 release, with an older one it worked fine) is that this element ends up somehow in the XML, and is becomes invalid, and YALV! cannot load it:

`<nlog:properties />`

Not sure if this is important or not, but I also have a `<log4j:properties>` element, and this one is valid.

Thank you

### PR DESCRIPTION
**Pull request by snakefoot**
Fixes #2088

### CODE REVIEW

**Comment by 304NotModified** [comment]
changes without newlines:

https://github.com/NLog/NLog/pull/2090/files?w=1

File: src/NLog/Layouts/Log4JXmlEventLayout.cs [hunk 1]
```diff
@@ -58,6 +58,26 @@ public Log4JXmlEventLayout()
         public Log4JXmlEventLayoutRenderer Renderer { get; private set; }
 
         /// <summary>
+        /// Gets or sets a value indicating whether to include contents of the <see cref="MappedDiagnosticsContext"/> dictionary.
+        /// </summary>
+        /// <docgen category='Payload Options' order='10' />
+        public bool IncludeMdc { get { return Renderer.IncludeMdc; } set { Renderer.IncludeMdc = value; } }
```
Comment (304NotModified) [inline src/NLog/Layouts/Log4JXmlEventLayout.cs]: maybe we should add an interface that dictates the properties shared by Log4JXmlEventLayout.cs and Log4JXmlEventLayoutRenderer.cs ? 

Then it's more clear those are coupled. What do you think?

File: src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs [hunk 2]
```diff
@@ -329,6 +332,28 @@ protected override void Append(StringBuilder builder, LogEventInfo logEvent)
...
+                            string propertyKey = XmlHelper.XmlConvertToString(contextProperty.Key);
+                            if (string.IsNullOrEmpty(propertyKey))
+                                continue;
+
+                            string propertyValue = XmlHelper.XmlConvertToString(contextProperty.Value);
+                            if (propertyValue == null)
+                                continue;
+
+                            xtw.WriteStartElement("log4j", "data", dummyNamespace);
+                            xtw.WriteAttributeSafeString("name", propertyKey);
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs]: in the feature we should unduplicate this cdeo

File: src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs [hunk 3]
```diff
@@ -329,6 +332,28 @@ protected override void Append(StringBuilder builder, LogEventInfo logEvent)
                 }
 #endif
 
+                if (this.IncludeAllProperties)
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs]: this a new feature, isn't it?

File: src/NLog/MappedDiagnosticsContext.cs [hunk 4]
```diff
@@ -50,9 +50,15 @@ public static class MappedDiagnosticsContext
     {
         private static readonly object dataSlot = ThreadLocalStorageHelper.AllocateDataSlot();
 
-        private static IDictionary<string, object> ThreadDictionary
+        private static readonly IDictionary<string, object> EmptyDefaultDictionary = new SortHelpers.ReadOnlySingleBucketDictionary<string, object>();
+
+        private static IDictionary<string, object> GetThreadDictionary(bool create = true)
```
Comment (304NotModified) [inline src/NLog/MappedDiagnosticsContext.cs]: could you please document when we should set create to `false`?

File: src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs (hunk 3 above)
Comment (snakefoot) [inline src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs]: Yes

File: src/NLog/Layouts/Log4JXmlEventLayout.cs (hunk 1 above)
Comment (snakefoot) [inline src/NLog/Layouts/Log4JXmlEventLayout.cs]: No idea. Just thought it was weird that the Layout didn't have access to all the fancy options on the layout-renderer.

Comment (304NotModified) [inline src/NLog/Layouts/Log4JXmlEventLayout.cs]: OK, added for the feature https://github.com/NLog/NLog/issues/2091

File: src/NLog/MappedDiagnosticsContext.cs (hunk 4 above)
Comment (snakefoot) [inline src/NLog/MappedDiagnosticsContext.cs]: Updated XML-documentation

File: src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs (hunk 2 above)
Comment (snakefoot) [inline src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs]: Removed the duplicate code.

Comment (304NotModified) [inline src/NLog/LayoutRenderers/Log4JXmlEventLayoutRenderer.cs]: 👍 👍

File: tests/NLog.UnitTests/LayoutRenderers/Log4JXmlTests.cs [hunk 5]
```diff
@@ -156,6 +156,10 @@ public void Log4JXmlTest()
                                         break;
 #endif
 
+                                    case "nlogPropertyKey":
```
Comment (304NotModified) [inline tests/NLog.UnitTests/LayoutRenderers/Log4JXmlTests.cs]: isn't it strange we have now "nlogPropertyKey" in "log4j" and "nlog" (https://github.com/snakefoot/NLog/blob/2f5e3cced2fb1e56846e68e260c28c7d237bccfb/tests/NLog.UnitTests/LayoutRenderers/Log4JXmlTests.cs#L192)

Comment (snakefoot) [inline tests/NLog.UnitTests/LayoutRenderers/Log4JXmlTests.cs]: Not sure I understand. It is part of the standard log4j-properties because of IncludeAllProperties=true. The non-standard nlog-properties can only be handled by custom parsers.

Comment (304NotModified) [inline tests/NLog.UnitTests/LayoutRenderers/Log4JXmlTests.cs]: OK thanks

**Comment by 304NotModified** [comment]
Could you please update the docs? Thanks!

**Comment by snakefoot** [comment]
Updated the following wiki pages:

https://github.com/NLog/NLog/wiki/Log4JXMLEvent-Layout-Renderer
https://github.com/NLog/NLog/wiki/Log4JXmlEventLayout
