### PR TITLE
Overhaul ExceptionLayoutRenderer

### LINKED ISSUE #1016: Overhaul ExceptionLayoutRenderer Methods
*Modify the Delegates to be func.

Delegate Definition / Signature:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
private delegate void ExceptionDataTarget(StringBuilder sb, Exception ex);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Methods which will be affected by this

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
AppendMessage
AppendMethod
AppendStackTrace
AppendToString
AppendType
AppendShortType
AppendData
CompileFormat
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### PR DESCRIPTION
**Pull request by Page-Not-Found**
* Added enums so that the API can set with enums instead of strings.
* Converted all delegates to action delegates.

fixes #1016

### CODE REVIEW

**Comment by 304NotModified** [comment]
This weekend I will review it.

**Comment by 304NotModified** [comment]
fixes https://github.com/NLog/NLog/issues/1016

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 1]
```diff
@@ -142,13 +167,13 @@ protected override void Append(StringBuilder builder, LogEventInfo logEvent)
...
                 string separator = string.Empty;
 
-                foreach (ExceptionDataTarget targetRenderFunc in this.exceptionDataTargets)
+                foreach (ExceptionRenderingFormat renderingFormat in this.Formats)
                 {
                     sb2.Append(separator);
-                    targetRenderFunc(sb2, logEvent.Exception);
+                    _functions[renderingFormat](sb2, logEvent.Exception);
+
                     separator = this.Separator;
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: this is a bit strange, do you agree? (assignment can be outside the loop)

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 2]
```diff
@@ -142,13 +167,13 @@ protected override void Append(StringBuilder builder, LogEventInfo logEvent)
                 var sb2 = new StringBuilder(128);
                 string separator = string.Empty;
 
-                foreach (ExceptionDataTarget targetRenderFunc in this.exceptionDataTargets)
+                foreach (ExceptionRenderingFormat renderingFormat in this.Formats)
                 {
                     sb2.Append(separator);
-                    targetRenderFunc(sb2, logEvent.Exception);
+                    _functions[renderingFormat](sb2, logEvent.Exception);
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: please create a variable of `  _functions[renderingFormat]` (just for readability).

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 3]
```diff
@@ -157,10 +182,10 @@ protected override void Append(StringBuilder builder, LogEventInfo logEvent)
                     sb2.Append(this.InnerExceptionSeparator);
 
                     separator = string.Empty;
-                    foreach (ExceptionDataTarget targetRenderFunc in this.innerExceptionDataTargets ?? this.exceptionDataTargets)
+                    foreach (ExceptionRenderingFormat renderingFormat in this.InnerFormats ?? this.Formats)
                     {
                         sb2.Append(separator);
-                        targetRenderFunc(sb2, currentException);
+                        _functions[renderingFormat](sb2, currentException);
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: idem

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 4]
```diff
@@ -157,10 +182,10 @@ protected override void Append(StringBuilder builder, LogEventInfo logEvent)
...
                         separator = this.Separator;
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: idem

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 5]
```diff
@@ -52,9 +52,16 @@ public class ExceptionLayoutRenderer : LayoutRenderer
     {
         private string format;
         private string innerFormat = string.Empty;
-        private ExceptionDataTarget[] exceptionDataTargets;
-        private ExceptionDataTarget[] innerExceptionDataTargets;
-        
+        private Dictionary<ExceptionRenderingFormat, Action<StringBuilder, Exception>> _functions = new Dictionary<ExceptionRenderingFormat, Action<StringBuilder, Exception>>() {
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: please add `readonly`

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 6]
```diff
@@ -268,52 +293,54 @@ protected virtual void AppendData(StringBuilder sb, Exception ex)
...
         {
+            List<ExceptionRenderingFormat> formats = new List<ExceptionRenderingFormat>();
             string[] parts = formatSpecifier.Replace(" ", string.Empty).Split(',');
-            var dataTargets = new List<ExceptionDataTarget>();
 
             foreach (string s in parts)
             {
+                ExceptionRenderingFormat renderingFormat;
+
                 switch (s.ToUpper(CultureInfo.InvariantCulture))
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: I think it's still nice to rewrite the `swich` to a static dictionary. We have discussed this before I think, but we can write an overload. 

the dictionary is better for the code complexity (arcording to Cyclomatic complexity) and so easier to mainain.

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 7]
```diff
@@ -268,52 +293,54 @@ protected virtual void AppendData(StringBuilder sb, Exception ex)
...
                         break;
-
                     case "DATA":
-                        dataTargets.Add(AppendData);
+                        renderingFormat = ExceptionRenderingFormat.Data;
                         break;
-
                     default:
                         InternalLogger.Warn("Unknown exception data target: {0}", s);
+                        renderingFormat = ExceptionRenderingFormat.NotSet;
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: Proposal: remove `NotSet` and change `ExceptionRenderingFormat renderingFormat` to `ExceptionRenderingFormat? renderingFormat`

File: src/NLog/Config/ExceptionRenderingFormat.cs [hunk 8]
```diff
@@ -0,0 +1,81 @@
...
+{
+    /// <summary>
+    /// Format of the excpetion output to the specific target.
+    /// </summary>
+    public enum ExceptionRenderingFormat
+    {
+        /// <summary>
+        /// This is for internal NLog Library usage. This is required we would a default value in switch cases. 
+        /// </summary>
+        NotSet = -1,
```
Comment (304NotModified) [inline src/NLog/Config/ExceptionRenderingFormat.cs]: This is not needed :)

See notes at the usage of `NotSet`. 

This one should be removed.

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 9]
```diff
@@ -268,52 +293,54 @@ protected virtual void AppendData(StringBuilder sb, Exception ex)
...
                         break;
                 }
-            }
+                if (renderingFormat != ExceptionRenderingFormat.NotSet)
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: this will be a null check

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 10]
```diff
@@ -268,52 +293,54 @@ protected virtual void AppendData(StringBuilder sb, Exception ex)
             }
         }
 
-        private ExceptionDataTarget[] CompileFormat(string formatSpecifier)
+        /// <summary>
+        /// Split the string and then compile into list of Rendering formats.
+        /// </summary>
+        /// <param name="formatSpecifier"></param>
+        /// <returns></returns>
+        private List<ExceptionRenderingFormat> CompileFormat(string formatSpecifier)
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: please add `static`

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 11]
```diff
@@ -66,8 +73,6 @@ public ExceptionLayoutRenderer()
             this.MaxInnerExceptionLevel = 0;
         }
 
-        private delegate void ExceptionDataTarget(StringBuilder sb, Exception ex);
-
         /// <summary>
         /// Gets or sets the format of the output. Must be a comma-separated list of exception
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: please refer to Formats + ExceptionRenderingFormat

with
`<see cref="Formats"/>` and `<see cref="ExceptionRenderingFormat"/>`

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 12]
```diff
@@ -85,7 +90,7 @@ public string Format
             set
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: same, refer to InnerFormats + ExceptionRenderingFormat

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 13]
```diff
@@ -131,6 +136,26 @@ public string InnerFormat
         public string InnerExceptionSeparator { get; set; }
 
         /// <summary>
+        ///  Gets the formats of the output of inner exceptions to be rendered in target.
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: please ref to `Format` with the `<see` tag.

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 14]
```diff
@@ -131,6 +136,26 @@ public string InnerFormat
...
+        {
+            get;
+            private set;
+        }
+
+        /// <summary>
+        ///  Gets the formats of the output to be rendered in target.
+        /// </summary>
+        /// <docgen category='Rendering Options' order='10' />
+        public List<ExceptionRenderingFormat> InnerFormats
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: please ref to `InnerFormat` with the `<see` tag.

**Comment by 304NotModified** [comment]
hey @Page-Not-Found 

I reviewed the code. It looks really good, I added some notes for docs and some code improvements.
I'm happy we can remove the `NotSet` enum value. :)

Let me know what you think. I still think the switch to dictionary is a great improvement (I use it always for "conversion", but let me know if you think otherwise.

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs (hunk 1 above)
Comment (Page-Not-Found) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: For the first level the separator is not required and so the separator is assigned after the first loop.

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs (hunk 6 above)
Comment (Page-Not-Found) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: I am not sure I understand you. But the current code is with the Dictionary.

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs (hunk 4 above)
Comment (Page-Not-Found) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: What does this mean?

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs (hunk 11 above)
Comment (Page-Not-Found) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: Is this one you are looking for?

~~~~~~~~~~~~~~~~~~~~~
/// <summary>
        /// Gets or sets the format of the output. Must be a comma-separated list of exception
        /// properties: Message, Type, ShortType, ToString, Method, StackTrace.
        /// This parameter value is case-insensitive.
        /// </summary>
        /// <see cref="Formats"/>
        /// <see cref="ExceptionRenderingFormat"/>
        /// <docgen category='Rendering Options' order='10' />
        [DefaultParameter]
        public string Format
        {
            get
            {
                return this.format;
            }

            set
            {
                this.format = value;
                Formats = CompileFormat(value);
            }
        }

**Comment by Page-Not-Found** [comment]
>Let me know what you think. I still think the switch to dictionary is a great improvement (I use it always for conversions) but let me know if you think otherwise.

I think the initial format to list conversion is currently in the switch. Do you mean that needs to be changed?

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
private static List<ExceptionRenderingFormat> CompileFormat(string formatSpecifier)
        {
            List<ExceptionRenderingFormat> formats = new List<ExceptionRenderingFormat>();
            string[] parts = formatSpecifier.Replace(" ", string.Empty).Split(',');

            foreach (string s in parts)
            {
                ExceptionRenderingFormat? renderingFormat = null;

                switch (s.ToUpper(CultureInfo.InvariantCulture))
                {
                    case "MESSAGE":
                        renderingFormat = ExceptionRenderingFormat.Message;
                        break;
                    case "TYPE":
                        renderingFormat = ExceptionRenderingFormat.Type;
                        break;
                    case "SHORTTYPE":
                        renderingFormat = ExceptionRenderingFormat.ShortType;
                        break;
                    case "TOSTRING":
                        renderingFormat = ExceptionRenderingFormat.ToString;
                        break;
                    case "METHOD":
                        renderingFormat = ExceptionRenderingFormat.Method;
                        break;
                    case "STACKTRACE":
                        renderingFormat = ExceptionRenderingFormat.StackTrace;
                        break;
                    case "DATA":
                        renderingFormat = ExceptionRenderingFormat.Data;
                        break;
                    default:
                        InternalLogger.Warn("Unknown exception data target: {0}", s);                        
                        break;
                }
                if (renderingFormat != null)
                    formats.Add(renderingFormat.Value);

            }
            return formats;
        }
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by 304NotModified** [comment]
Yes,  that would be a great improvement!

**Comment by Page-Not-Found** [comment]
I will write up a proposed code change and put up here again.

**Comment by Page-Not-Found** [comment]
Here you go with a sample code
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
private static readonly Dictionary<String, ExceptionRenderingFormat> _formatsMapping = new Dictionary<string, ExceptionRenderingFormat>
{
	{"MESSAGE",ExceptionRenderingFormat.Message}, 
	{"TYPE", ExceptionRenderingFormat.Type}, 
	{"SHORTTYPE",ExceptionRenderingFormat.ShortType}, 
	{"TOSTRING",ExceptionRenderingFormat.ToString}, 
	{"METHOD",ExceptionRenderingFormat.Method}, 
	{"STACKTRACE", ExceptionRenderingFormat.StackTrace}, 
	{"DATA",ExceptionRenderingFormat.Data}, 
};

/// <summary>
        /// Split the string and then compile into list of Rendering formats.
        /// </summary>
        /// <param name="formatSpecifier"></param>
        /// <returns></returns>
        private static List<ExceptionRenderingFormat> CompileFormat(string formatSpecifier)
        {
            List<ExceptionRenderingFormat> formats = new List<ExceptionRenderingFormat>();
            string[] parts = formatSpecifier.Replace(" ", string.Empty).Split(',');

            foreach (string s in parts)
            {
                ExceptionRenderingFormat? renderingFormat = null;
                if (_formatsMapping.ContainsKey(s))
                {
                    renderingFormat = _formatsMapping[s];
                    formats.Add(renderingFormat.Value);
                }
                else
                {
                    InternalLogger.Warn("Unknown exception data target: {0}", s);
                }

            }
            return formats;
        }

**Comment by 304NotModified** [comment]
Yes! that was what I really like.

some last improvements:

1. pass `StringComparer.OrdinalIgnoreCase` to the contructor of dictionary:
 `_formatsMapping = new Dictionary<string, ExceptionRenderingFormat>(StringComparer.OrdinalIgnoreCase)`

2. `formatSpecifier.Replace(" ", string.Empty).Split(',')`, is this `  formatSpecifier.Split('.', StringSplitOptions.RemoveEmptyEntries)` ?

3. use ` dict.TryGetValue()` instead if `Contains` and `[..]` - that one is 2 times faster and more logical here.

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 15]
```diff
@@ -176,8 +224,8 @@ protected override void Append(StringBuilder builder, LogEventInfo logEvent)
         /// Appends the Message of an Exception to the specified <see cref="StringBuilder" />.
         /// </summary>
         /// <param name="sb">The <see cref="StringBuilder"/> to append the rendered data to.</param>
-        /// <param name="ex">The exception containing the Message to append.</param>
-        protected virtual void AppendMessage(StringBuilder sb, Exception ex)
+        /// <param name="ex">The exception containing the Message to append.</param>        
+        private static void AppendMessage(StringBuilder sb, Exception ex)
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: Why move to private? This isnt backwards-compatible now?

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 16]
```diff
@@ -268,52 +316,30 @@ protected virtual void AppendData(StringBuilder sb, Exception ex)
...
         {
-            string[] parts = formatSpecifier.Replace(" ", string.Empty).Split(',');
-            var dataTargets = new List<ExceptionDataTarget>();
+            List<ExceptionRenderingFormat> formats = new List<ExceptionRenderingFormat>();
+            string[] parts = formatSpecifier.Replace(" ", string.Empty).Split(new string[] { "," }, StringSplitOptions.RemoveEmptyEntries);
 
             foreach (string s in parts)
             {
-                switch (s.ToUpper(CultureInfo.InvariantCulture))
+                ExceptionRenderingFormat renderingFormat;
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: Really nice :)

**Comment by 304NotModified** [comment]
I think this is ready to merge? 

I added one backwards-compatibly question. That's the last thing.

**Comment by Page-Not-Found** [comment]
I am with limited internet access. Will get back to this once I am back.

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs (hunk 15 above)
Comment (Page-Not-Found) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: For Adding this into the Dictionary we have to move this to Private. We cannot maintain both the instance and static methods also. 

The other solution which I could think of is making a internal static class and mapping them together.

Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: I get your point. With the virtual protected method (e.g. AppendMessage), you can do two things:

1. replace behavior(virtual).
2. call the method myself. This is the private/protected. 

I don't know how an `Action` will work with `virtual`, but I think this doens't work? So 
1 and 2 are now breaking changes. 2 is easy to fix, but 1 is tricky. I think you warned me before about the breaking change of 1, but I missed to see it :|

Any thoughts? Breaking changes aren't nice.

Comment (Page-Not-Found) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: As I said earlier 
>The other solution which I could think of is making a internal static class and having the new methods in them and call them from the virtual methods. What do you say?

Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: Oops. Missed that one on mobile. 

Do you think it's a good solution?

Comment (Page-Not-Found) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: >Do you think it's a good solution?
Atleast for now and them remove the virtual methods in upcoming releases.

Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: > Atleast for now and them remove the virtual methods in upcoming releases.

Doesn't sound future proof to me. Well, mabye was the dictionary (my) mistake and not a good step?

Comment (Page-Not-Found) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: I will see if I can fine someother solution.

Comment (Page-Not-Found) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: There are two options now

1. Remove the Dict (`_renderingfunctions`) which will fall back to the loop and the switch case.
2. Change all the methods back to virtual method and make the dictionary as INSTANCE type rather than a static variable. 

When I try to change the method to public virtual, the dictionary isn't allowing. Which is understandable. I see the below error

`A field initializer cannot reference the non-static field, method, or property 'NLog.LayoutRenderers.ExceptionLayoutRenderer.AppendMessage(System.Text.StringBuilder, System.Exception)'`

Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: I think 2 won't work with virtual? Action and virtual won't work together? (method override in sub class, maybe unit test it?)  If it does, I prefer 2 and otherwise we should do 1.

**Comment by Page-Not-Found** [comment]
@304NotModified  I was able to change the methods back to virtual and override them as well. Added one more commit to the PR. Let me know what you feel.

File: tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs [hunk 17]
```diff
@@ -562,5 +563,135 @@ private class GenericClass<TA, TB, TC>
...
+
+
+            Assert.Equal(ExceptionRenderingFormat.ShortType, elr.Formats[0]);
+            Assert.Equal(ExceptionRenderingFormat.Message, elr.Formats[1]);
+
+            Assert.Equal(ExceptionRenderingFormat.Message, elr.InnerFormats[0]);
+        }
+
+        [Fact]
+        public void CustomExceptionLayoutRendrerInnerExceptionTest()
```
Comment (304NotModified) [inline tests/NLog.UnitTests/LayoutRenderers/ExceptionTests.cs]: Thanks for this test :D

**Comment by 304NotModified** [comment]
Cool! Merged it finally! 

Very happy with the end result. It's a big improvement :)
