### PR TITLE
FileTarget: Fix file archive race-condition.

### LINKED ISSUE #1608: Cannot create a file when that file already exists.
Type: Bug

NLog version: 4.3.7

Platform: .NET 4.6.1

Current NLog config

```xml
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" throwExceptions="true">
    <targets>
        <target name="BackgroundUploaderLog" xsi:type="File" maxArchiveFiles="5" archiveNumbering="Rolling" archiveAboveSize="20" concurrentWrites="true" filename="App.log" />
    </targets>
    <rules>
      <logger name="*" minlevel="Debug" writeTo="BackgroundUploaderLog" />
    </rules>
  </nlog>

```

In case of a BUG:

- What is the current result?
An exception is likely to occur if the attached project is run through visual studio . Try to run few times, should be reproducible at least one time for each 5 executions.  Note that the exception is less likely to be thrown whilst running in command line.

- What is the expected result?
Write the logs without exception.

- Please post full exception details (message, stacktrace, inner exceptions)

```
Unhandled Exception: System.IO.IOException: Cannot create a file when that file
already exists.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Bo
olean checkHost)
   at NLog.Targets.FileTarget.RollArchiveForward(String existingFileName, String
 newFileName)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String patter
n, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String patter
n, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String patter
n, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String patter
n, Int32 archiveNumber)
   at NLog.Targets.FileTarget.RollArchivesForward(String fileName, String patter
n, Int32 archiveNumber)
   at NLog.Targets.FileTarget.DoAutoArchive(String fileName, LogEventInfo eventI
nfo)
   at NLog.Targets.FileTarget.ProcessLogEvent(LogEventInfo logEvent, String file
Name, Byte[] bytesToWrite)
   at NLog.Targets.FileTarget.Write(LogEventInfo logEvent)
   at NLog.Targets.Target.Write(AsyncLogEventInfo logEvent)
   at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent)
   at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetL
istHead, LogEventInfo logEvent, AsyncContinuation onException)
   at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogE
ventInfo logEvent, LogFactory factory)
   at NLog.Logger.WriteToTargets(Type wrapperType, LogEventInfo logEvent)
   at NLog.Logger.Log(Type wrapperType, LogEventInfo logEvent)
   at Common.Logging.NLog.NLogLogger.WriteInternal(LogLevel logLevel, Object mes
sage, Exception exception) in c:\_oss\common-logging\src\Common.Logging.NLog10\L
ogging\NLog\NLogLogger.cs:line 951
   at Common.Logging.NLog.NLogLogger.Debug(Object message) in c:\_oss\common-log
ging\src\Common.Logging.NLog10\Logging\NLog\NLogLogger.cs:line 272
   at ConsoleApplication1.LongRunningProcess.Run() in c:\users\fernando\document
s\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\LongRunnin
gProcess.cs:line 24
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

- Are there any work arrounds? 
No. I tried to use keepFileOpen = true and an AsyncWrapper.
I also tried to use the version 4.4.0 Beta V15, but with the same results.

[ConsoleApplication1.zip](https://github.com/NLog/NLog/files/449208/ConsoleApplication1.zip)

### PR DESCRIPTION
**Pull request by bhaeussermann**
Fix #1608

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1646)

### CODE REVIEW

**Comment by 304NotModified** [comment]
Guess we don't have a `Mutex` on Silverlight

File: src/NLog/Internal/FileAppenders/BaseFileAppender.cs [hunk 1]
```diff
@@ -158,6 +174,78 @@ protected void FileTouched(DateTime dateTime)
...
+            // A mutex name must not exceed MAX_PATH (260) characters
+            if (mutexName.Length <= maxMutexNameLength)
+            {
+                return mutexName;
+            }
+
+            // The unusual case of the path being too long; let's hash the canonical name,
+            // so it can be safely shortened and still remain unique
+            string hash;
+            using (MD5 md5 = MD5.Create())
```
Comment (304NotModified) [inline src/NLog/Internal/FileAppenders/BaseFileAppender.cs]: not sure if this is the best approach. We could also substring it and add a guid?

Comment (304NotModified) [inline src/NLog/Internal/FileAppenders/BaseFileAppender.cs]: ah well, it was already there?

Comment (bhaeussermann) [inline src/NLog/Internal/FileAppenders/BaseFileAppender.cs]: Yes, this code came from `MutexMultiProcessFileAppender`. Adding a Guid won't work, because a different process will compute a different Guid for the same file. We need the same file to have the same mutex-name across processes.

**Comment by bhaeussermann** [comment]
@304NotModified unfortunately, I cannot produce the error from #1608 anymore, even with the old NLog.dll (it stopped happening; I don't know why). We must probably make a hidden package again so viseu can test again.

File: src/NLog/Internal/FileAppenders/BaseFileAppender.cs (hunk 1 above)
Comment (304NotModified) [inline src/NLog/Internal/FileAppenders/BaseFileAppender.cs]: ok thanks! :)
