### PR TITLE
Handle duplicate attributes (error or using first occurence)

### LINKED ISSUE #1659: Logger configuration attributes issue with duplicate attributes
**Type**: Bug

**NLog version**: 4.3.9

**Platform**: Net 4.6 

**Current NLog config**: xml 

``` xml
<nlog throwExceptions="false" internalLogFile="nloglog.txt" internalLogLevel="Trace">
    <targets>
      <target name="Console" type="ColoredConsole" useDefaultRowHighlightingRules="true" layout="${longdate} | ${message}"/>
    </targets>
    <rules>
      <logger name="*" minlevel="Info" writeTo="Console" minLevel="Info"/>
    </rules>
  </nlog>

```

The logger declaration contains two attributes with names different only in case ("minlevel" and "minLevel")
- What is the current result?
  Logger does not log anything
- What is the expected result?
  Logger writes logs or throws an exception
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
  Yes. Logger does not write even an internal log
- Are there any work arrounds?
  No
- Is there a version in which it did worked? 
  Don't know
- Can you help us by writing an unit test?
  https://github.com/Falconwatch/NLogAttributes

### PR DESCRIPTION
**Pull request by nazim9214**
Resolves #1659 .
1. Logger now can write logs when config has duplicate attributes (first occurence is taken)
2. If throwExceptions or throwConfigExceptions option is on - exception is thrown.

---

This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1732)

### CODE REVIEW

**Comment by 304NotModified** [comment]
hey thanks!

I just checked the code, but something is not clear to me. If we allow/ignore duplicate attributes, why do we need the "last error"?

**Comment by nazim9214** [comment]
In current implementation, we throw first of these exceptions in elements tree if throwConfigExceptions is enabled. I can't throw it immediately, because configuration must be loaded, to setup all needed options to Logger (for example throwConfigException option, targets etc.).

If something is not written well or not clear, i can rewrite this code. What do you think?

**Comment by 304NotModified** [comment]
@nazim9214 

We could also throw the exception here? https://github.com/NLog/NLog/pull/1732/files#diff-0e7810ffc1c0cd264e0012f3310ed9c2R254

(after checking `configExcception.MustBeRethrown()` ?

**Comment by nazim9214** [comment]
If I correctly  understood all the logic:
1. Firstly, we are parsing XML configuration into NLogXmlElement tree.
2. Next, we are calling ParseTopLevel, and filling LogFactory properties with corresponding values.

If exception is thrown here https://github.com/NLog/NLog/pull/1732/files#diff-0e7810ffc1c0cd264e0012f3310ed9c2R254, the second part won't be executed. All LogFactory properties will be unfilled (LogFactory.ThrowExceptions, LogFactory.ThrowConfigExceptions, targets etc.), so ```configExcception.MustBeRethrown()``` - will always return "false" for this case (it uses LogManager.ThrowConfigExceptions, LogManager.ThrowExceptions).

**Comment by 304NotModified** [comment]
Ah now I fully understand it  :) Thx!

I think it's a bit uncommon to store an exception and to throw it later. Maybe we could replace _lastParsingError with _parseError(s) and as `string` or `List<string>`. Then in step 2 we do:

a. check if there are any errors
b. if so, then check if `ThrowConfigExceptions` is enabled
c. if so, then throw **one** Exception with all the messages
d. if not, then write all the messages as warning to the `InternalLogger`.

What do you think?

**Comment by nazim9214** [comment]
Good idea! I'll do it soon.

**Comment by 304NotModified** [comment]
👍

File: src/NLog/Config/NLogXmlElement.cs [hunk 1]
```diff
@@ -212,19 +221,59 @@ public void AssertName(params string[] allowedNames)
             throw new InvalidOperationException("Assertion failed. Expected element name '" + string.Join("|", allowedNames) + "', actual: '" + this.LocalName + "'.");
         }
 
+        /// <summary>
+        /// Try to get all errors occured during xml parsing.
+        /// A return value indicates whether there any error.
+        /// </summary>
+        /// <param name="errors">Array of error messages</param>
+        public bool TryGetParsingErrors(out string[] errors)
```
Comment (304NotModified) [inline src/NLog/Config/NLogXmlElement.cs]: I don't prefer `out` parameters. Could be change this to `public string GetParsingErrors()`? 

The "try" pattern is nice, but IMO more suitable on parsing.

**Comment by nazim9214** [comment]
Thanks for the advice!

File: src/NLog/Config/NLogXmlElement.cs [hunk 2]
```diff
@@ -212,19 +221,59 @@ public void AssertName(params string[] allowedNames)
...
+        {
+            var errors = GetParsingErrorsInternal().ToArray();
+            if (errors.Length == 0) return null;
+            return string.Join(Environment.NewLine, errors);
+        }
+
+        /// <summary>
+        /// Returns all parsing errors from current and all child elements.
+        /// </summary>
+        private IEnumerable<string> GetParsingErrorsInternal()
```
Comment (304NotModified) [inline src/NLog/Config/NLogXmlElement.cs]: Thanks for the changes!

As from our part, we find it important to have a good public API. I think it would be better API if I could read the details, so that the errors aren't joined to a single string. Do you agree?

The easiest way is to make `GetParsingErrorsInternal()` public and rename it to `GetParsingErrors()` (and drop the `GetParsingErrors()`). What do you think?

File: tests/NLog.UnitTests/NLog.UnitTests.mono.csproj [hunk 3]
```diff
@@ -250,4 +252,7 @@
       <Name>SampleExtensions.mono</Name>
     </ProjectReference>
   </ItemGroup>
+  <ItemGroup>
+    <Service Include="{82A7F48D-3B50-4B1E-B82E-3ADA8210C358}" />
```
Comment (304NotModified) [inline tests/NLog.UnitTests/NLog.UnitTests.mono.csproj]: any idea what this is?

**Comment by nazim9214** [comment]
Wow, i'm failing my tests:) Sorry, too hurried

File: src/NLog/Config/XmlLoggingConfiguration.cs [hunk 4]
```diff
@@ -446,6 +445,33 @@ private void Initialize(XmlReader reader, string fileName, bool ignoreErrors)
...
+        /// Checks whether any error during XML configuration parsing has occured.
+        /// If there are any and <c>ThrowConfigExceptions</c> or <c>ThrowExceptions</c>
+        /// setting is enabled - throws <c>NLogConfigurationException</c>, otherwise
+        /// just write an internal log at Warn level.
+        /// </summary>
+        /// <param name="rootContentElement">Root NLog configuration xml element</param>
+        private void CheckParsingErrors(NLogXmlElement rootContentElement)
+        {
+            var parsingErrors = rootContentElement.GetParsingErrors().ToArray();
+            if(!parsingErrors.Any())
```
Comment (304NotModified) [inline src/NLog/Config/XmlLoggingConfiguration.cs]: this should be `if(parsingErrors.Any())`  I guess ;)

**Comment by 304NotModified** [comment]
yes a `!` mistake. 

the CI services are helpful today :)

**Comment by 304NotModified** [comment]
:lgtm:

---

Reviewed 5 of 9 files at r1, 1 of 3 files at r2, 2 of 2 files at r4, 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1732#-:-KWUrJHogNpC9Jw0r4DL:bnfp4nl)*

**Comment by 304NotModified** [comment]
Merged :) Thanks!!!
