### PR TITLE
Database target entity framework connection string

### LINKED ISSUE #98: Support for Entity Framework connection strings
<p>Hello. NLog does not currently seem to support Entity Framework connection strings: DatabaseTarget.InitializeTarget() throws an exception because it cannot create a DbProviderFactory from the EF providerName=&quot;System.Data.EntityClient&quot;.</p>

<p>&nbsp;</p>

<p>Unfortunately, because DatabaseTarget is sealed I can&#39;t just customize the connection string behavior as I would with log4net.</p>

<p>&nbsp;</p>

<p>Please consider adding direct support for the EF provider type (might not be too hard, a regular connection string is indeed embedded in there) or unsealing DatabaseTarget.</p>

<p>&nbsp;</p>

<p>Thank you!</p>

### PR DESCRIPTION
**Pull request by snakefoot**
Embedded the code from  #2308 directly into DatabaseTarget. Resolves #98 

Since "provider" is a common keyword in the connectionstring, and no one have requested NLog to parse it, then I have decided to only parse it when the connectionstring seems to come from entity framework.

### CODE REVIEW

File: tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs [hunk 1]
```diff
@@ -1228,6 +1228,29 @@ public void DontRequireProviderNameInAppConfig()
...
+            databaseTarget.ConnectionStringsSettings = new ConnectionStringSettingsCollection()
+            {
+                new ConnectionStringSettings("test_connectionstring_with_providerName",
+                    "metadata=res://*/Model.csdl|res://*/Model.ssdl|res://*/Model.msl;provider=System.Data.SqlClient;provider connection string=\"data source=192.168.0.100;initial catalog=TEST_DB;user id=myUser;password=SecretPassword;multipleactiveresultsets=True;application name=EntityFramework\"",
+                    "System.Data.EntityClient"),
+            };
+
+            databaseTarget.Initialize(null);
+            Assert.NotNull(databaseTarget.ProviderFactory);
+            Assert.Equal(typeof(SqlClientFactory), databaseTarget.ProviderFactory.GetType());
```
Comment (304NotModified) [inline tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs]: Could you please add an assert here for the connectionstring?

**Comment by 304NotModified** [comment]
thx!
