### PR TITLE
WindowsPhone is Silverlight with more file access

### LINKED ISSUE #1875: LogManager.GetCurrentClassLogger() failed on WP81 Silverlight apps [fix proposed]
Hi! 

**Type**: Bug

**NLog version**: v4.0.30319

**Platform**: Windows Phone 8.1 Silverlight apps

**Current NLog config** (xml or C#, if relevant)

Today I tried to repeat steps from this tutorial but in terms of Windows Phone 8.1 http://nlog-project.org/2011/01/09/nlog-for-windows-phone-7.html

Latest sources have only Windows Phone 8.0 support (and auto-upgrade causes removal of some methods in "Logger1.cs" file so you can't compile without reverting that file back to depot version). And even after resolving that caveats, you to receive a runtime error while trying to create any logger instance.

Config file is the same as described in the tutorial:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <targets>
    <target xsi:type="LogReceiverService" name="webService" endpointAddress="http://localhost:5000/LogReceiver.svc"/>
  </targets>

  <rules>
    <logger name="*" minlevel="Debug" writeTo="webService" />
  </rules>
</nlog>
```

Code usage is from the tutorial too:
private static NLog.Logger logger = NLog.LogManager.GetCurrentClassLogger();

- What is the current result?
Exception: System.MethodAccessException occurred
  HResult=-2146233072
  Message=Attempt by security transparent method 'NLog.LogFactory.get_Configuration()' to access security critical method 'System.Windows.Application.GetResourceStream(System.Uri)' failed.
  Source=NLog
  StackTrace:
       at NLog.LogFactory.get_Configuration()
  InnerException: 

- What is the expected result?
Normal logger creation

- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
Have no idea how to achieve this as apps crashes at early stage (static init)

- Please post full exception details (message, stacktrace, inner exceptions)
Additional information: Attempt by security transparent method 'NLog.LogFactory.get_Configuration()' to access security critical method 'System.Windows.Application.GetResourceStream(System.Uri)' failed.

- Are there any work arrounds? yes/no
You can amend the sources in two places:
1) XmlLoggingConfiguration.cs
===============
---  #if SILVERLIGHT
+++ #if SILVERLIGHT && !WINDOWS_PHONE
                newFileName = newFileName.Replace("\\", "/");
                if (Application.GetResourceStream(new Uri(newFileName, UriKind.Relative)) != null)
#else
                if (File.Exists(newFileName))
#endif
===============

 2) LogFactory.cs
===============
---  #if SILVERLIGHT
+++ #if SILVERLIGHT && !WINDOWS_PHONE
                            Uri configFileUri = new Uri(configFile, UriKind.Relative);
                            if (Application.GetResourceStream(configFileUri) != null)
                            {
                                LoadLoggingConfiguration(configFile);
                                break;
                            }
#else
                            if (File.Exists(configFile))
                            {
                                LoadLoggingConfiguration(configFile);
                                break;
                            }
#endif
===============

- Is there a version in which it did worked? 
Not found

- Can you help us by writing an unit test?
Not sure

### PR DESCRIPTION
**Pull request by snakefoot**
Attempt to fix #1875

---
This change is [Reviewable](https://reviewable.io/reviews/nlog/nlog/1881)

### CODE REVIEW

File: src/NLog/Common/InternalLogger.cs [hunk 1]
```diff
@@ -357,14 +357,14 @@ public static void LogAssemblyVersion(Assembly assembly)
         {
             try
             {
-#if SILVERLIGHT || __IOS__ || __ANDROID__
-                Info(assembly.FullName);
-#else
+#if !SILVERLIGHT && !__IOS__ && !__ANDROID__
```
Comment (304NotModified) [inline src/NLog/Common/InternalLogger.cs]: Why this change? (I see nothing got changed functional). It's this a better style?

It will lead to potential conflicts on the coreCLR branch.

File: src/NLog/Internal/FileAppenders/BaseFileAppender.cs [hunk 2]
```diff
@@ -231,7 +231,7 @@ protected FileStream CreateFileStream(bool allowFileSharedWriting)
             throw new InvalidOperationException("Should not be reached.");
         }
 
-#if !SILVERLIGHT && !MONO && !__IOS__ && !__ANDROID__
+#if !SILVERLIGHT && !__IOS__ && !__ANDROID__ && !MONO
```
Comment (304NotModified) [inline src/NLog/Internal/FileAppenders/BaseFileAppender.cs]: idem. potentional conflict

File: src/NLog/Internal/FileCharacteristicsHelper.cs [hunk 3]
```diff
@@ -45,18 +45,16 @@ internal abstract class FileCharacteristicsHelper
         /// </summary>
         public static FileCharacteristicsHelper CreateHelper(bool forcedManaged)
         {
-#if SILVERLIGHT
-            return new PortableFileCharacteristicsHelper();
-#else
+#if !SILVERLIGHT && !__IOS__ && !__ANDROID__
```
Comment (304NotModified) [inline src/NLog/Internal/FileCharacteristicsHelper.cs]: good  one, although I prefer not to change the order again ;)

**Comment by snakefoot** [comment]
The change in order was to make everything more consistent, now the non-mobile platform check looks like this everywhere:

> #if !SILVERLIGHT && !__IOS__ && !__ANDROID__

But I can save that for later, if it causes too much trouble for CoreClr-branch.,

File: src/NLog/Internal/FileCharacteristicsHelper.cs (hunk 3 above)
Comment (snakefoot) [inline src/NLog/Internal/FileCharacteristicsHelper.cs]: Well not changing order, but removing code.

**Comment by 304NotModified** [comment]
> But I can save that for later, if it causes too much trouble for CoreClr-branch.,

yes please. Thanks!

**Comment by snakefoot** [comment]
> yes please. Thanks!

Done

**Comment by 304NotModified** [comment]
Reviewed 17 of 28 files at r1, 3 of 10 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1881)*

**Comment by 304NotModified** [comment]
Reviewed 2 of 10 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlog/nlog/1881)*

**Comment by 304NotModified** [comment]
Thanks man! merged!

**Comment by 304NotModified** [comment]
looks like this one is giving issues: https://ci.appveyor.com/project/nlog/nlog/build/4.4.4171

**Comment by snakefoot** [comment]
> The master build fails :(

Think if you re-trigger the build, then it succeeds:

https://ci.appveyor.com/project/nlog/nlog/build/4.4.4177

**Comment by snakefoot** [comment]
> The master build fails :(

Was able to reproduce the bug locally, and it seems the following happens:

The test uses ArchiveEvery = FileArchivePeriod.Minute, so if the test is executed at exact 12:59:59.999 then it will trigger an extra unexpected archive operation. As the LogEvent timestamp will then be one-minute older than the creation-time of the current log-file.

The archive operation fails because the log-filename (based on current-time) and the generated archive-filename (based on file-write-time) becomes the same. Because the archive-filename already exists then it attempts to append the contents of the log-filename to the archive-filename and it of course fails.

We could change the ArchiveEvery to Year, and then the test DeleteArchiveFilesByDateWithDateName would only fail at new years eve. 

We could also consider to change FileTarget.ArchiveFile() to check if fileName and archiveFileName is the same, and if so then just do nothing but doing a InternalLogger.Info()

**Comment by snakefoot** [comment]
Created #1886
