### PR TITLE
DatabaseTarget - Added AllowDbNull for easier support for nullable pa…

### LINKED ISSUE #4070: DB null layout render doesn't work in whenEmpty
**NLog version**: 4.7.2
**Platform**: .Net 4.8
**Current NLog config**

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog internalLogLevel="Warn"
  internalLogFile="C:\Temp\NLog.Internal.txt"
  internalLogToConsole="true"
  autoReload="true" 
  throwExceptions="true"
  xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <targets async="true">
    <target xsi:type="Database" name="DbDefault"
            connectionStringName = "frameworkLogging"
            commandText = "INSERT INTO Logs ([Date], [Level], [Logger], [Message], [Exception], [LogGuid], [Username], [Source], [LogGroupingIdentifier]) VALUES (@log_date, @level, @logger, @message, @exception, @logGuid, @username, @source, @logGroupingIdentifier)" keepConnection="true">
      ...
      <parameter name="@exception" layout="${exception:format=tostring:whenEmpty=${db-null}}" />
      ...
    </target>
    ...
</nlog>
```

- What is the current result?
When exception is empty/null, an empty string.
- What is the expected result?
When exception is empty/null, a NULL value is written to the database.
- Did you checked the [Internal log](https://github.com/NLog/NLog/wiki/Internal-Logging)?
trace: `2020-08-04 10:27:20.6864 Trace   DatabaseTarget: Parameter: '@exception' = '' (String)`
- Are there any workarounds? no
- Is there a version in which it did work?
Not that I know of
- Can you help us by writing an unit test?
Not sure

### PR DESCRIPTION
**Pull request by snakefoot**
Instead of doing this:

`<parameter name="@exception" layout="${exception:format=tostring:whenEmpty=${db-null}}" parameterType="System.Object" 
/>`
`<parameter name="@correlationid" layout="${activityid:whenEmpty=${db-null}}" dbType="DbType.Guid" parameterType="System.Object" />`

Then one can do this:

`<parameter name="@exception" layout="${exception:format=tostring}" allowDbNull="true" />`
`<parameter name="@exception" layout="${activityid}" dbType="DbType.Guid" allowDbNull="true" />`

Trying to resolve #4070

### CODE REVIEW

File: src/NLog/Targets/DatabaseParameterInfo.cs [hunk 1]
```diff
@@ -134,6 +134,13 @@ public DatabaseParameterInfo(string parameterName, Layout parameterLayout)
         [DefaultValue(null)]
         public CultureInfo Culture { get; set; }
 
+        /// <summary>
+        /// Gets or sets whether empty value should translate into DbNull
+        /// </summary>
+        /// <docgen category='Parameter Options' order='8' />
+        [DefaultValue(false)]
+        public bool AllowDbNull { get; set; }
```
Comment (304NotModified) [inline src/NLog/Targets/DatabaseParameterInfo.cs:142]: What about EmptyToDbNull or Nullable?

Comment (snakefoot) [reply src/NLog/Targets/DatabaseParameterInfo.cs:142]: Well in SQL language it is often called allow NULL. So that is why I like the **Allow**-part. But because in DotNet then it is not an actually null-reference but instead the artificial **DbNull**. This gives **AllowDbNull**

**Comment by snakefoot** [comment]
> And is this difficult to unit test?

I seldom write unit-tests when making prototypes. I have never used the DatabaseTarget for anything myself. I was actually hoping that you or @leonardder would chime in and acknowledge / reject the direction.

**Comment by snakefoot** [comment]
@304NotModified Now added unit-test that puts some more concrete around the name `AllowDbNull` :)

File: src/NLog/Targets/DatabaseParameterInfo.cs (hunk 1 above)
Comment (304NotModified) [reply src/NLog/Targets/DatabaseParameterInfo.cs:142]: Clear, but it does more than allow, it translates. I'm not sure how clear that is from the name (see also the description, it's using the term translate and not allow). But I also like to have feedback if others :)

Comment (snakefoot) [reply src/NLog/Targets/DatabaseParameterInfo.cs:142]: Have updated to source-code comment about having allow null configured for the database-column :)

**Comment by leonardder** [comment]
Would this pr cover the case where

1. The database column allows nulls and is of a string type
2. An empty string (so not a null) is written to the target?

**Comment by snakefoot** [comment]
NLog does not know the difference between null and string.Empty:


- AllowDbNull = false will change null into string.Empty when DbType is string (else default of the expected value type, ex 0 when integer)

- AllowDbNull = true will change null and string.Empty into DbNull


Sent from my Sony Xperia


---- Leonard de Ruijter wrote ----


Would this pr cover the case where

  1.  The database column allows nulls and is of a string type
  2.  An empty string (so not a null) is written to the target?

File: tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs [hunk 2]
```diff
@@ -607,7 +607,13 @@ public void LevelParameterTest(DbType? dbType, bool noRawValue, string expectedV
         [InlineData("${event-properties:almostAsIntProp}", DbType.Int32, 124)]
         [InlineData("${event-properties:almostAsIntProp}", DbType.Int64, (long)124)]
         [InlineData("${event-properties:almostAsIntProp}", DbType.AnsiString, " 124 ")]
-        public void GetParameterValueTest(string layout, DbType dbtype, object expected, bool convertToDecimal = false)
+        [InlineData("${event-properties:NullRawValue}", DbType.AnsiString, "")]
+        [InlineData("${event-properties:NullawValue}", DbType.Int32, 0)]
```
Comment (leonardder) [inline tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs:611]:
```suggestion
        [InlineData("${event-properties:NullRawValue}", DbType.Int32, 0)]
```

File: tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs [hunk 3]
```diff
@@ -607,7 +607,13 @@ public void LevelParameterTest(DbType? dbType, bool noRawValue, string expectedV
...
+        [InlineData("${event-properties:NullRawValue}", DbType.AnsiString, null, true)]
+        [InlineData("${event-properties:NullRawValue}", DbType.Int32, null, true)]
```
Comment (leonardder) [inline tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs:613]: It would be nice if you could add tests for Guid as well:

```suggestion
        [InlineData("${event-properties:NullRawValue}", DbType.Int32, null, true)]
        [InlineData("${event-properties:NullRawValue}", DbType.Guid, null, true)]
```

File: tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs [hunk 4]
```diff
@@ -607,7 +607,13 @@ public void LevelParameterTest(DbType? dbType, bool noRawValue, string expectedV
...
+        [InlineData("", DbType.AnsiString, null, true)]
+        [InlineData("", DbType.Int32, null, true)]
```
Comment (leonardder) [inline tests/NLog.UnitTests/Targets/DatabaseTargetTests.cs:615]:
```suggestion
        [InlineData("", DbType.Int32, null, true)]
        [InlineData("", DbType.Guid, null, true)]
```

**Comment by snakefoot** [comment]
@leonardder Have fixed the spelling error, and added some testing of `DbType.Guid`

Introduced a small inconsistency, so if the `LogEventInfo.Properties`-dictionary contains `string.Empty` value, then it will respect the value and not convert into DbNull when using `AllowDbNull = true`.

**Comment by 304NotModified** [comment]
Merged! Great feature!
