### PR TITLE
Bugfix: Broken xml stops logging

### LINKED ISSUE #273: NLog stops logging when the config file is broken, and then config is repaired (autoreload)
Reproducting the issue
1. Use autoreload="True" parameter in config file.
2. Start application - NLog working fine.
3. Invalidate XML structure in NLog.config file (i.e. delete some closing tag), save the file, then NLog will stop logging.
4. Change NLog.config to the previous valid state, save it - NLog still not logging until the application is restarted.

### PR DESCRIPTION
**Pull request by 304NotModified**
fixes #273 

problem: `XmlLoggingConfiguration.Initialize` eats exception with invalid
XML. ALso `XmlLoggingConfiguration.Reload` never returns `null`.
So the `null` check is not enough

- added `InitializeSucceeded` (nullable `bool`) in `XmlLoggingConfiguration`
- checks also `InitializeSucceeded`. If` false`, DON't apply the config.

Result: invalidating the XML won't stop logging, the old config will be used.
Also, the auto reload won't turned to `false` (the default)

The unit tests proves the solution and also the previous problem.

### CODE REVIEW

**Comment by 304NotModified** [comment]
The changes are small, but a review would be wise because there is a new public property added.

**Comment by 304NotModified** [comment]
Unit tests are working local. Dunno why AppVeyor is complaining

**Comment by 304NotModified** [comment]
Fixed: )

**Comment by Xharze** [comment]
Looks good to me. Just wondering about all the linebreaks between the tests? Any reason for this?

**Comment by 304NotModified** [comment]
The line breaks is just bad coding style of me ;) - I like white space when programming.

Most of the time I let Resharper fix this, but too bad the NLog code style if really different then my Resharper profile (I like `var` for example)

I will fix this code styling thing with a commit.

**Comment by 304NotModified** [comment]
wtf. Removed newlines and now are the unit tests failing?

**Comment by 304NotModified** [comment]
Unit tests are fixed and PR is ready for merge after review.

File: src/NLog/Config/XmlLoggingConfiguration.cs [hunk 1]
```diff
@@ -62,6 +62,8 @@ public class XmlLoggingConfiguration : LoggingConfiguration
 
         private string originalFileName;
 
+
```
Comment (Xharze) [inline src/NLog/Config/XmlLoggingConfiguration.cs]: Could you delete these extra newlines?

File: tests/NLog.UnitTests/Config/IncludeTests.cs [hunk 2]
```diff
@@ -87,6 +92,8 @@ public void IncludeTest()
             }
         }
 
+
```
Comment (Xharze) [inline tests/NLog.UnitTests/Config/IncludeTests.cs]: Please delete extra linebreaks

**Comment by Xharze** [comment]
@304NotModified Good work, please see my comments, otherwise it looks great

**Comment by 304NotModified** [comment]
Thanks. Unneeded newlines removed!
