### PR TITLE
Fix tests to ensure all AsyncTargetWrapper's are closed.

### LINKED ISSUE #1251: Fix unstable test InternalLoggerTests
Result of #1213 , some unit tests are unstable, like some InternalLoggerTests 

See

https://ci.appveyor.com/project/nlog/nlog/build/4.0.1935
https://ci.appveyor.com/project/nlog/nlog/build/4.0.1947

Expected:

```
  Fatal FFF Exception: NLog.NLogConfigurationException: config error
  Trace TTT Exception: NLog.NLogConfigurationException: config error ---> System.Exception: e2 --->

```

But we get (sometimes)

```
  Fatal FFF Exception: NLog.NLogConfigurationException: config error
                Trace AsyncWrapper: ProcessPendingEvents
                Trace AsyncWrapper: ProcessPendingEvents
                Trace AsyncWrapper: Flushing 100 events.
                Trace AsyncWrapper: Flushing 100 events.
  Trace TTT Exception: NLog.NLogConfigurationException: config error ---> System.Exception: e2 --->

```

### PR DESCRIPTION
**Pull request by bhaeussermann**
Fixes #1251

### CODE REVIEW

File: src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs [hunk 1]
```diff
@@ -213,7 +213,7 @@ protected virtual void StartLazyWriterTimer()
         }
 
         /// <summary>
-        /// Starts the lazy writer thread.
+        /// Stops the lazy writer thread.
         /// </summary>
         protected virtual void StopLazyWriterThread()
```
Comment (304NotModified) [inline src/NLog/Targets/Wrappers/AsyncTargetWrapper.cs]: LOL nice typo spotted!

File: tests/NLog.UnitTests/Targets/FileTargetTests.cs [hunk 2]
```diff
@@ -2280,14 +2282,21 @@ public void Dont_throw_Exception_when_archiving_is_enabled()
 </nlog>
 ");
 
-            NLog.LogManager.GetLogger("Test").Info("very important message");
+                NLog.LogManager.GetLogger("Test").Info("very important message");
+            }
+            finally
+            {
+                LogManager.Configuration = null;
```
Comment (304NotModified) [inline tests/NLog.UnitTests/Targets/FileTargetTests.cs]: I tried something slimiar, but  in the ctor of NLogTestBase (as xUnit create a new instance of the test class every test)

https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/NLogTestBase.cs#L64

So any idea why that won't work?

File: tests/NLog.UnitTests/Targets/LogReceiverWebServiceTargetTests.cs [hunk 3]
```diff
@@ -190,10 +190,18 @@ public void NoEmptyEventLists()
...
+            try
+            {
+                asyncTarget.Initialize(configuration);
+                asyncTarget.WriteAsyncLogEvents(new[] { LogEventInfo.Create(LogLevel.Info, "logger1", "message1").WithContinuation(ex => { }) });
+                Thread.Sleep(1000);
+                Assert.Equal(1, target.SendCount);
+            }
+            finally
+            {
+                asyncTarget.Close();
```
Comment (304NotModified) [inline tests/NLog.UnitTests/Targets/LogReceiverWebServiceTargetTests.cs]: Idem did something like this:

https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/NLogTestBase.cs#L62

**Comment by 304NotModified** [comment]
Thanks! 

No sure why this would work as it looks like a lot to my previous approach. Any ideas? (see code comments)

File: tests/NLog.UnitTests/Targets/FileTargetTests.cs (hunk 2 above)
Comment (bhaeussermann) [inline tests/NLog.UnitTests/Targets/FileTargetTests.cs]: When I debug I see that [https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/NLogTestBase.cs#L64](https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/NLogTestBase.cs#L64) does work. In fact, I don't think this test was a problem. I changed this merely for good measure (good practice).

I think the actual problem is `AsyncTargetWrapperTests` (see next comment).

File: tests/NLog.UnitTests/Targets/LogReceiverWebServiceTargetTests.cs (hunk 3 above)
Comment (304NotModified) [inline tests/NLog.UnitTests/Targets/LogReceiverWebServiceTargetTests.cs]: edit: I guess I see the issue. The asyncTarget isn't in logmanager.configuration hence it is not closed with `LogManager.Configuration.Close();`

**Comment by 304NotModified** [comment]
\0/

time to rebase all other branches (PR's)

File: tests/NLog.UnitTests/Targets/LogReceiverWebServiceTargetTests.cs (hunk 3 above)
Comment (bhaeussermann) [inline tests/NLog.UnitTests/Targets/LogReceiverWebServiceTargetTests.cs]: This is similar to the code in `AsyncTargetWrapperTests`. Running the tests (with the old code) through the debugger shows that the `AsyncTargetWrapper` is not closed. 

[https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/NLogTestBase.cs#L62](https://github.com/NLog/NLog/blob/master/tests/NLog.UnitTests/NLogTestBase.cs#L62) does not take care of this, because in these tests the `AsyncTargetWrapper` is not in the configuration.

After the change debugging the tests confirms that the `AsyncTargetWrapper` is closed.
