### PR TITLE
Fix HttpGet protocol for WebService

### LINKED ISSUE #701: WebserviceTarget - HttpGet is broken (Exception thrown)
The current implementation of `WebServiceTarget` throws an Exception with `HttpGet`. 

```
 Result Message:	System.Net.ProtocolViolationException : Cannot send a content-body with this verb-type.
 Result StackTrace:	
 at System.Net.HttpWebRequest.CheckProtocol(Boolean onRequestStream)
    at System.Net.HttpWebRequest.BeginGetRequestStream(AsyncCallback callback, Object state)
    at NLog.Targets.WebServiceTarget.<>c__DisplayClass1.<DoInvoke>b__0(AsyncCallback r) in NLog\src\NLog\Targets\WebServiceTarget.cs:line 151
    at NLog.Targets.WebServiceTarget.DoInvoke(Object[] parameters, AsyncContinuation continuation, HttpWebRequest request, Func`2 beginFunc, Func`2 getStreamFunc) in NLog\src\NLog\Targets\WebServiceTarget.cs:line 218
    at NLog.Targets.WebServiceTarget.DoInvoke(Object[] parameters, AsyncContinuation continuation) in NLog\src\NLog\Targets\WebServiceTarget.cs:line 154
    at NLog.Targets.MethodCallTargetBase.Write(AsyncLogEventInfo logEvent) in NLog\src\NLog\Targets\MethodCallTargetBase.cs:line 79
    at NLog.Targets.Target.WriteAsyncLogEvent(AsyncLogEventInfo logEvent) in NLog\src\NLog\Targets\Target.cs:line 215
    at NLog.LoggerImpl.WriteToTargetWithFilterChain(TargetWithFilterChain targetListHead, LogEventInfo logEvent, AsyncContinuation onException) in NLog\src\NLog\LoggerImpl.cs:line 194
    at NLog.LoggerImpl.Write(Type loggerType, TargetWithFilterChain targets, LogEventInfo logEvent, LogFactory factory) in NLog\src\NLog\LoggerImpl.cs:line 97
    at NLog.Logger.WriteToTargets(LogLevel level, IFormatProvider formatProvider, String message) in NLog\src\NLog\Logger.cs:line 480
    at NLog.Logger.Info(String message) in NLog\src\NLog\Logger1.cs:line 636
    at NLog.UnitTests.Targets.WebServiceTargetTests.<>c__DisplayClassc.<TestWebserviceCall_get>b__b() in NLog\tests\NLog.UnitTests\Targets\WebServiceTargetTests.cs:line 326
    at NLog.UnitTests.Targets.WebServiceTargetTests.StartOwinTest(Action tests) in NLog\tests\NLog.UnitTests\Targets\WebServiceTargetTests.cs:line 422
    at NLog.UnitTests.Targets.WebServiceTargetTests.TestWebserviceCall_get() in NLog\tests\NLog.UnitTests\Targets\WebServiceTargetTests.cs:line 323
```

See unit test `WebServiceTargetTests.WebserviceTest_restapi_httpget` (now skipped!)  and #699

### PR DESCRIPTION
**Pull request by MikeFH**
Fixes #701 
Reenables the `WebserviceTest_restapi_httpget` unit test, not sure if other tests are needed.
Not sure either if the `spaceAsPlus` parameter for the `UrlHelper.UrlEncode()` should be true or false

### CODE REVIEW

**Comment by 304NotModified** [comment]
Thanks! Will try to review it today!

File: src/NLog/Targets/WebServiceTarget.cs [hunk 1]
```diff
@@ -250,6 +250,45 @@ protected override void DoInvoke(object[] parameters, AsyncContinuation continua
...
+            if (this.Protocol != WebServiceProtocol.HttpGet)
+            {
+                return this.Url;
+            }
+            
+            //if the protocol is HttpGet, we need to add the parameters to the query string of the url
+            var queryParameters = new StringBuilder();
+            string separator = string.Empty;
+            int i = 0;
+            foreach (MethodCallParameter parameter in this.Parameters)
```
Comment (304NotModified) [inline src/NLog/Targets/WebServiceTarget.cs]: Looks good, but I think `for` is better if we already need an `i`. Do you agree?

File: src/NLog/Targets/WebServiceTarget.cs [hunk 2]
```diff
@@ -250,6 +250,45 @@ protected override void DoInvoke(object[] parameters, AsyncContinuation continua
...
+                queryParameters.Append(separator);
+                queryParameters.Append(parameter.Name);
+                queryParameters.Append("=");
+                queryParameters.Append(UrlHelper.UrlEncode(Convert.ToString(parameterValues[i], CultureInfo.InvariantCulture), true));
+                separator = "&";
+                i++;
+            }
+
+            var builder = new UriBuilder(this.Url);
+            if (builder.Query != null && builder.Query.Length > 1)
```
Comment (304NotModified) [inline src/NLog/Targets/WebServiceTarget.cs]: can you add some comments here WHY we doing this?

**Comment by 304NotModified** [comment]
Hi, added some small comments.

>not sure if other tests are needed.

If we looks at the [code cov](https://codecov.io/github/NLog/NLog/commit/5accf5fc70a7c6990cfcde1298e48b99fd4bc085), we see some yellow and red. It would be nice if we add an new unit test, or expand the current unit test, so  everything is covered (green). 

> Not sure either if the spaceAsPlus parameter for the UrlHelper.UrlEncode() should be true or false

It seems that `false` is the safe option: 
http://stackoverflow.com/a/2678602/201303

File: src/NLog/Targets/WebServiceTarget.cs [hunk 3]
```diff
@@ -250,6 +250,45 @@ protected override void DoInvoke(object[] parameters, AsyncContinuation continua
...
+            //if the protocol is HttpGet, we need to add the parameters to the query string of the url
+            var queryParameters = new StringBuilder();
+            string separator = string.Empty;
+            int i = 0;
+            foreach (MethodCallParameter parameter in this.Parameters)
+            {
+                queryParameters.Append(separator);
+                queryParameters.Append(parameter.Name);
+                queryParameters.Append("=");
+                queryParameters.Append(UrlHelper.UrlEncode(Convert.ToString(parameterValues[i], CultureInfo.InvariantCulture), true));
```
Comment (304NotModified) [inline src/NLog/Targets/WebServiceTarget.cs]: spaceAsPlus should be `false`

File: src/NLog/Targets/WebServiceTarget.cs (hunk 1 above)
Comment (MikeFH) [inline src/NLog/Targets/WebServiceTarget.cs]: Completely agree. I copied the logic from the `PrepareHttpRequest` method and did not notice `Parameters` was an `IList<>`

File: src/NLog/Targets/WebServiceTarget.cs (hunk 2 above)
Comment (MikeFH) [inline src/NLog/Targets/WebServiceTarget.cs]: Yes. I know it looks weird, but that's how the property is supposed to be used : [UriBuilder.Query doc](https://msdn.microsoft.com/en-us/library/system.uribuilder.query.aspx). Is it OK to include a link to this page in the comment ?

**Comment by MikeFH** [comment]
I tried to fix the different issues. Appveyor build is passing on my repo so i don't really know why it's failing here.

**Comment by 304NotModified** [comment]
That's an unstable test. Will try a rebuild

**Comment by 304NotModified** [comment]
Cool! It has been merged. Thanks!

**Comment by 304NotModified** [comment]
Also thanks for nice communication, like the  `spaceAsPlus` thing. :)

**Comment by MikeFH** [comment]
My pleasure :)
