### PR TITLE
${Exception} - Added Format options: HResult and Properties

### LINKED ISSUE #3519: Custom renderer for exceptions
**NLog version**: 4.6.6

**Platform**: All

**Current NLog config** (xml or C#, if relevant)

```xml
<nlog>
  <targets>
    <target xsi:type="File" name="f" fileName="${basedir}/logs/${shortdate}.log"
            layout="${longdate} ${uppercase:${level}} ${message} ${exception:format=message}" />
  </targets>
  <rules>
    <logger name="*" minlevel="Debug" writeTo="f" />
  </rules>
</nlog>
```

Most of the exception subclasses have custom properties which are very useful when diagnosing the cause of the exception. For example `Win32Exception` has a `NativeErrorCode` property. If we want the property to get logged we need to add a catch block specifically for `Win32Exception` and log ` NativeErrorCode`. This can lead to useless and duplicated catch blocks.

I propose adding a way to create custom renderers for specific exception subclasses so the instances of that exception type will be formatted with that custom renderer. Here is an example for registering custom exception renderer for `Win32Exception` which will log `NativeErrorCode` in addition to default data logged for every exception:

```
ExceptionLayoutRenderer.RegisterExceptionRenderer<Win32Exception>(exception => $"NativeErrorCode: {exception.NativeErrorCode}");
```

With this renderer logging an instance of `Win32Exception` will result in this output:

`2019-07-19 23:44:53.9813 ERROR  The system cannot find the file specified NativeErrorCode: 2`

### PR DESCRIPTION
**Pull request by snakefoot**
Trying to resolve #3519 together with #3610

```c#
NLog.LogManager.LogFactory.RegisterObjectTransformation<System.Net.WebException>(ex =>new {
    Type = ex.GetType().ToString(),
    Message = ex.Message,
    StackTrace = ex.StackTrace,
    Source = ex.Source,
    InnerException = ex.InnerException,
    Status = ex.Status,
    Response = ex.Response.ToString(),  // Call your custom method to render stream as string
});
```

Then you can do this in NLog.config:

```xml
${exception:format=Properties}
```

Then it will output `Status` and `Response`  like they were entries in the Exception.Data-dictionary.

Alternative one could just setup a conversion of the type `System.Net.WebResponse` so it becomes a string. Then any object logged by NLog that contains a `System.Net.WebResponse` will automatically output its string-value.

### CODE REVIEW

**Comment by snakefoot** [comment]
@Giorgi Any input whether this extra option would help solve your issue?

You would have to register a type-reflector using the interface from  #3610 that detects WebException. And converts it into a dictionary of name and value pairs. Ex:

```
"Type" => ex.GetType()
"Message" => ex.Message
"TargetSite" => ex.TargetSite
"Source" => ex.Source
"Data" => ex.Data
"InnerException" => ex.InnerException
"Response" => ConvertStreamToString(ex.Response.GetResponseStream())
```

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 1]
```diff
@@ -66,8 +68,41 @@ public class ExceptionLayoutRenderer : LayoutRenderer, IRawValue
...
+                                                                                                        {"PROPERTIES",ExceptionRenderingFormat.Properties},
                                                                                                     };
 
+        private static readonly HashSet<string> ExcludeDefaultProperties = new HashSet<string>(new[] {
+            "Type",
+            nameof(Exception.Data),
+#if !SILVERLIGHT
+            nameof(Exception.HelpLink),
+#else
+            "HelpLink",
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: While I like `nameof`s, I think just "HelpLink" is more clear? The code is more complicated with all the `#if` (and more difficult to refactor, instead of easier to refactor with `nameof`)

Comment (304NotModified) [reply src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: same for below.

Please remove the `#if`s

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 2]
```diff
@@ -382,6 +419,21 @@ protected virtual void AppendSource(StringBuilder sb, Exception ex)
...
 
+        /// <summary>
+        /// Appends the HResult of an Exception to the specified <see cref="StringBuilder" />.
+        /// </summary>
+        /// <param name="sb">The <see cref="StringBuilder"/> to append the rendered data to.</param>
+        /// <param name="ex">The Exception whose HResult should be appended.</param>
+        protected virtual void AppendHResult(StringBuilder sb, Exception ex)
+        {
+#if NET45
+            if (ex.HResult != 0 && ex.HResult != 1)
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: 0 are 1 are special? Is that somewhere documented? Maybe reference here? 

I only see 0 here: https://docs.microsoft.com/en-us/windows/win32/seccrypto/common-hresult-values

Comment (304NotModified) [reply src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: we could use reflection for older .NET :angel:

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs [hunk 3]
```diff
@@ -411,6 +463,30 @@ protected virtual void AppendSerializeObject(StringBuilder sb, Exception ex)
...
+        {
+            string separator = string.Empty;
+            var exceptionProperties = ObjectReflectionCache.LookupObjectProperties(ex);
+            foreach (var property in exceptionProperties)
+            {
+                if (ExcludeDefaultProperties.Contains(property.Name))
+                    continue;
+
+                var propertyValue = property.Value;
+                if (propertyValue == null || string.IsNullOrEmpty(propertyValue as string))
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: is this on purpose that we use here `as string` and we `ToString`? The latter could also return empty? (if so, please add a comment line, thanks!)

Comment (snakefoot) [reply src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: Fixed

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs (hunk 2 above)
Comment (snakefoot) [reply src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: Added const int documentation

File: src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs (hunk 1 above)
Comment (snakefoot) [reply src/NLog/LayoutRenderers/ExceptionLayoutRenderer.cs]: Removed the `#if`

**Comment by Giorgi** [comment]
@snakefoot Can you add couple of configuration examples to show how to use the new rendering options ?

**Comment by Giorgi** [comment]
Looks good to me. Thanks!

**Comment by 304NotModified** [comment]
Thanks!!

**Comment by 304NotModified** [comment]
Updated https://github.com/NLog/NLog/wiki/Exception-layout-renderer !
