### PR TITLE
StackTraceLayoutRenderer with Raw format should display source FileName

### LINKED ISSUE #2074: Stacktrace doesn't show file lines and file names
**Type**: Bug

**NLog version**:   4.4.6

**Platform**: .Net 4.5

**Current NLog config**

```xml
<nlog>
  <targets>
    <target name="logfile" xsi:type="File" fileName="file.txt" layout="${stacktrace:format=raw}"/>
  </targets>
  <rules>
    <logger name="*" minlevel="Trace" writeTo="logfile" />
  </rules>
</nlog>

```
My current log with that configuration is:
_ExecuteAssembly at offset 127 in file:line:column <filename unknown>:0:0
nExecuteAssembly at offset 0 in file:line:column <filename unknown>:0:0
Main at offset 710 in file:line:column <filename unknown>:0:0_

I expect filelines and filenames to be in logfile.
I tried to do same thing with .NET diagnostic (something like _var frames = new StackTrace(true).GetFrames();_) and all filenames and filelines were showed correctly.

Project has full output debug info, all pdb-files are on their place.

I also tried to do that on NLog version 4.2.3 and received same result - no filelines and filenames.

### PR DESCRIPTION
**Pull request by snakefoot**
Attempt to fix #2074

### CODE REVIEW

File: tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs [hunk 1]
```diff
@@ -118,6 +118,27 @@ public void RenderStackTrace_DetailedFlat()
...
+            <nlog>
+                <targets><target name='debug' type='Debug' layout='${message} ${stacktrace:format=RawWithSource}' /></targets>
+                <rules>
+                    <logger name='*' minlevel='Debug' writeTo='debug' />
+                </rules>
+            </nlog>");
+
+            RenderMe("I am:");
+
+            AssertDebugLastMessageContains("debug", "RenderStackTrace_RawWithSource at offset ");
```
Comment (304NotModified) [inline tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs]: not sure if this a useful test now. It can be still ` file:line:column <filename unknown>:0:0  ` ?

File: src/NLog/LayoutRenderers/StackTraceFormat.cs [hunk 2]
```diff
@@ -52,5 +52,10 @@ public enum StackTraceFormat
         /// Detailed flat format (method signatures displayed in a single line).
         /// </summary>
         DetailedFlat,
+
+        /// <summary>
+        /// Raw format (multiline with source info - as returned by StackFrame.ToString() method).
+        /// </summary>
+        RawWithSource,
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/StackTraceFormat.cs]: I'm doubting if we should patch `raw` instead of a new option (I know i proposed it earlier ;))

Printing ` file:line:column <filename unknown>:0:0  ` sounds useless to me and the default is `flat`. 

What do you think?

**Comment by 304NotModified** [comment]
Thanks! I was thinking to create this, but you we're faster :)

PS: please do use the `fixes` syntax. Thanks!

File: tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs (hunk 1 above)
Comment (snakefoot) [inline tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs]: Well it is combination of the 3 asserts, that all verifies the last logged message. See the original RenderStackTrace_Raw, which does the same.

Comment (304NotModified) [inline tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs]: yeah but should we not test that line number >0 ? 

Need a regex I guess

File: src/NLog/LayoutRenderers/StackTraceFormat.cs (hunk 2 above)
Comment (snakefoot) [inline src/NLog/LayoutRenderers/StackTraceFormat.cs]: I'm not using this LayoutRenderer, so fixing the existing Raw-format is fine with me.

File: tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs (hunk 1 above)
Comment (snakefoot) [inline tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs]: Well it is enough for me that it was able to capture the filename (StackTraceRendererTests.cs). Not wanting to dive into the StackTrace-formating abyss.

Comment (304NotModified) [inline tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs]: something like this?

```
string pattern = @"<(?<filename>.*?)>:(?<line>\d+):(?<col>\d+)";
```
https://regex101.com/r/JJ1tUk/1

Comment (snakefoot) [inline tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs]: I'm not committing any regex funkyness. Just close this PR, and create you own :)

File: src/NLog/LayoutRenderers/StackTraceFormat.cs (hunk 2 above)
Comment (304NotModified) [inline src/NLog/LayoutRenderers/StackTraceFormat.cs]: I think fix "raw" is more clear :) 

So remove and we need to document the change in Nlog 4.4.7.

File: tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs (hunk 1 above)
Comment (304NotModified) [inline tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs]: am I allowed to push on this branch?

Comment (snakefoot) [inline tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs]: "Allow edits from maintainers" is checked, so I guess you can knock yourself wild :)

File: tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs [hunk 3]
```diff
@@ -99,8 +99,9 @@ public void RenderStackTrace_raw()
 
             AssertDebugLastMessageContains("debug", "RenderStackTrace_raw at offset ");
             AssertDebugLastMessageContains("debug", "RenderMe at offset ");
-            AssertDebugLastMessageContains("debug", "<filename unknown>");
-
+#if !MONO
+            AssertDebugLastMessageContains("debug", "StackTraceRendererTests.cs");
```
Comment (304NotModified) [inline tests/NLog.UnitTests/LayoutRenderers/StackTraceRendererTests.cs]: 👍

**Comment by 304NotModified** [comment]
updated docs for this: https://github.com/NLog/NLog/wiki/Stack-Trace-Layout-Renderer
