### PR TITLE
NLog config file loading: use process name (e.g. applicationname.exe.nlog) when app.config is not available

### LINKED ISSUE #3156: Configuration in applicationname.exe.nlog files do not load
**NLog version**: 4.5.11
**Platform**:  .NET Core 2
**Current NLog config** (xml or C#, if relevant)

```xml
<?xml version="1.0" encoding="utf-8" ?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      throwExceptions="true" throwConfigExceptions="true">

  <targets>
    <target name="file" xsi:type="File"
            layout="${longdate} ${level} ${logger}: ${message} ${exception:format=ToString}"
            fileName="LogFiles/${shortdate}_LogFile.txt" keepFileOpen="true" encoding="utf-8"/>

    <target name="console" xsi:type="ColoredConsole"
            layout="${longdate} ${logger} ${level}: ${message} ${exception:format=ToString}"
            detectConsoleAvailable="true" />

  <rules>
    <logger name="*" minlevel="Debug" writeTo="file,console,viewer" />
  </rules>
</nlog>
```

According to https://github.com/nlog/nlog/wiki/Configuration-file it should be possible to have a configuration in a file called `program.exe.nlog` where `program.exe` is the executable for my program.

When the config file is in the `applicationname.exe.nlog` file, it does not work as expected.

Create a console application with the following `Program.cs`

```csharp
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            foreach (var target in LogManager.Configuration.AllTargets)
                Console.WriteLine("Target: {0}", target.Name);
        }
    }
```

Publish the program with `dotnet publish -c Release -r win-x64` and run the executable. The program crashes with `Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.`.

Rename the file to `nlog.config` and it works as expected.

### PR DESCRIPTION
**Pull request by snakefoot**
Trying to resolve #3156 for NetCore

### CODE REVIEW

File: src/NLog/Internal/ProcessIDHelper.cs [hunk 1]
```diff
@@ -31,55 +31,60 @@
...
         /// <summary>
         /// Gets current process name (excluding filename extension, if any).
         /// </summary>
-        public abstract string CurrentProcessBaseName { get; }
+        public string CurrentProcessBaseName => _currentProcessBaseName ?? (_currentProcessBaseName = string.IsNullOrEmpty(CurrentProcessFilePath) ? UnknownProcessName : Path.GetFileNameWithoutExtension(CurrentProcessFilePath));
+
+        /// <summary>
+        /// Initializes the ThreadIDHelper class.
+        /// </summary>
+        private static ProcessIDHelper CreateInstance()
```
Comment (304NotModified) [inline src/NLog/Internal/ProcessIDHelper.cs]: 👍 much better. Please rename it to just "Create" (it's a factory method) - and what other to create ;)

File: src/NLog/Config/LoggingConfigurationFileLoader.cs [hunk 2]
```diff
@@ -248,6 +248,28 @@ public IEnumerable<string> GetDefaultCandidateConfigFilePaths(string fileName)
...
+                {
+                    string processFilePath = ProcessIDHelper.Instance.CurrentProcessFilePath;
+                    string processDirectory = PathHelpers.TrimDirectorySeparators(Path.GetDirectoryName(processFilePath));
+                    if (!string.IsNullOrEmpty(entryAssemblyLocation) && !string.Equals(entryAssemblyLocation, processDirectory, StringComparison.OrdinalIgnoreCase))
+                    {
+                        // Handle dotnet-process loading .NET Core-assembly, or IIS-process loading website
+                        string assemblyFileName = Path.GetFileName(System.Reflection.Assembly.GetEntryAssembly().Location);
+                        if (!string.IsNullOrEmpty(assemblyFileName))
+                            yield return Path.Combine(entryAssemblyLocation, assemblyFileName + ".nlog");
+                        // Handle unpublished .NET Core Application
```
Comment (304NotModified) [inline src/NLog/Config/LoggingConfigurationFileLoader.cs]: Maybe a bit nitpicking, but I try to use those terms consistent :)

File: src/NLog/Internal/ProcessIDHelper.cs [hunk 3]
```diff
@@ -31,56 +31,61 @@
...
         /// <summary>
         /// Gets current process name (excluding filename extension, if any).
         /// </summary>
-        public abstract string CurrentProcessBaseName { get; }
+        public string CurrentProcessBaseName => _currentProcessBaseName ?? (_currentProcessBaseName = string.IsNullOrEmpty(CurrentProcessFilePath) ? UnknownProcessName : Path.GetFileNameWithoutExtension(CurrentProcessFilePath));
+
+        /// <summary>
+        /// Initializes the ThreadIDHelper class.
+        /// </summary>
+        private static ProcessIDHelper Create()
```
Comment (304NotModified) [inline src/NLog/Internal/ProcessIDHelper.cs]: FYI: I think "instance" in redundant, and most "factory methods" are called Create - so renamed it

File: src/NLog/Config/LoggingConfigurationFileLoader.cs [hunk 4]
```diff
@@ -248,6 +248,28 @@ public IEnumerable<string> GetDefaultCandidateConfigFilePaths(string fileName)
...
+                        assemblyFileName = Path.GetFileNameWithoutExtension(assemblyFileName);
+                        if (!string.IsNullOrEmpty(assemblyFileName))
+                            yield return Path.Combine(entryAssemblyLocation, assemblyFileName + ".exe.nlog");
+                    }
+                    else if (!string.IsNullOrEmpty(processFilePath))
+                    {
+                        yield return processFilePath + ".nlog";
+                    }
```
Comment (304NotModified) [inline src/NLog/Config/LoggingConfigurationFileLoader.cs]: Could you please elaborate the cases that here are implemented? Don't we need an unit test for this?

Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: Thought it was obvious as the other case is for running inside "dotnet.exe" then this case is for NOT running inside "dotnet.exe".

Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: Not that skilled with this build dynamic assemblies/processes and then running them. Find them very ugly and they only seem to be available for NetFramework (Not NetCore).

**Comment by snakefoot** [comment]
Actually think that `Win32ProcessIDHelper` could be thrown away. Think the original code was this (Causing overhead by allocating Process-object on every lookup.

> Process.GetCurrentProcess().Id

Without any caching. Causing it to be much slower than this code:

> NativeMethods.GetCurrentProcessId()

But later caching was added so there no overhead at all for either method. Could be nice to remove those Win32-native-methods.

File: src/NLog/Config/LoggingConfigurationFileLoader.cs (hunk 2 above)
Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: Potato potato :)

File: src/NLog/Config/LoggingConfigurationFileLoader.cs (hunk 4 above)
Comment (304NotModified) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: > Could you please elaborate the cases that here are implemented? Don't we need an unit test for this?

I meant all the 3? (not counted) test cases

File: src/NLog/Internal/ProcessIDHelper.cs (hunk 1 above)
Comment (snakefoot) [reply src/NLog/Internal/ProcessIDHelper.cs]: Think the whole instance thing should be removed. But not sure about the reason for the Win32-native-call. Since the values are cached, then I don't understand remark about Win32 is "without the overhead".

File: src/NLog/Config/LoggingConfigurationFileLoader.cs (hunk 4 above)
Comment (304NotModified) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: > Not that skilled with this build dynamic assemblies/processes and then running them. Find them very ugly and they only seem to be available for NetFramework (Not NetCore).

I think we need to mock them, but I forgot that the code in NLog is not very mockable :(

**Comment by 304NotModified** [comment]
> Could be nice to remove some of those Win32-native-methods.

Agree on that! Less code is better

File: src/NLog/Config/LoggingConfigurationFileLoader.cs (hunk 4 above)
Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: Will try and create new internal interface that merges ProcessIDHelper and IAppDomain. But not easy since IAppDomain and AppDomainWrapper are public. Then it should become easier to mock and exercise the config-lookup.

Comment (304NotModified) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: > Will try and create new internal interface that merges ProcessIDHelper and IAppDomain

Don't think that is needed. We need to inject them both, or a factory 

I can give it a try if you like

Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: Well to me IAppDomain is the hosting environment-interface. Don't need a new interface for every property in the hosting environment.

Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: > I can give it a try if you like

Would rather prefer you review and merge: https://github.com/NLog/NLog.Extensions.Logging/pull/263 :)

Comment (304NotModified) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: > Would rather prefer you review and merge: [NLog/NLog.Extensions.Logging#263](https://github.com/NLog/NLog.Extensions.Logging/pull/263) :)

done

So now: https://github.com/snakefoot/NLog/pull/7 :) (for the general idea)

Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: Already working on my own implementation of this mock. Your time would be better spent on all the other spider-issues in the hack-n-slash dungeon called NLog :)

Comment (304NotModified) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: What a spider issue? ❓

Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: Guess you have never played Diablo or other hack-n-slash dungeon-games. They usually have spiders. And spiders are good at making cobwebs. For NLog it means all the issues detected by the code-analyzers you have been so nice to enable.

**Comment by snakefoot** [comment]
@snakefoot Have squashed the commits, and ensured correct rename operations of the files.

File: src/NLog/Internal/Fakeables/IAppEnvironment.cs [hunk 5]
```diff
@@ -33,14 +33,28 @@
...
 namespace NLog.Internal.Fakeables
 {
+    using System.Collections.Generic;
+    using System.Xml;
+
     /// <summary>
     /// Abstract calls to File
     /// </summary>
-    internal interface IFile
+    internal interface IAppEnvironment
```
Comment (304NotModified) [inline src/NLog/Internal/Fakeables/IAppEnvironment.cs]: Why is this interface so fat? It's hard to reuse and doesn't follow the SRP. :/

Comment (snakefoot) [reply src/NLog/Internal/Fakeables/IAppEnvironment.cs]: Like you said it is an internal interface and it is the properties needed to mock the loading of NLog-config.

File: src/NLog/Config/LoggingConfigurationFileLoader.cs [hunk 6]
```diff
@@ -286,6 +338,7 @@ protected virtual void Dispose(bool disposing)
         public void Dispose()
         {
             Dispose(true);
+            GC.SuppressFinalize(this);
```
[the remark this answers is not in the document]
Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: Just removing noise from SonarLint.

File: src/NLog/Internal/Fakeables/IAppEnvironment.cs (hunk 5 above)
Comment (304NotModified) [reply src/NLog/Internal/Fakeables/IAppEnvironment.cs]: Please split it into separate interfaces. It's also important for internal code for a proper design

Comment (snakefoot) [reply src/NLog/Internal/Fakeables/IAppEnvironment.cs]: Have split into IFileSystem and IAppEnvironment

Comment (304NotModified) [reply src/NLog/Internal/Fakeables/IAppEnvironment.cs]: Thanks!

File: tests/NLog.UnitTests/ConfigFileLocatorTests.cs [hunk 7]
```diff
@@ -48,9 +45,234 @@ namespace NLog.UnitTests
...
+            LayoutRenderer.Register("the-answer", (info) => "42");
+            Layout l = "${the-answer}";
+            var result = l.Render(LogEventInfo.CreateNullEvent());
+            Assert.Equal("42", result);
+        }
+
+        [Fact]
+        void FuncLayoutRendererRegisterTest1WithXML()
+        {
+            LayoutRenderer.Register("the-answer", (info) => "42");
```
[the remark this answers is not in the document]
Comment (snakefoot) [reply tests/NLog.UnitTests/ConfigFileLocatorTests.cs]: Just me moving unit tests out of the `#if NETSTANDARD `-condition because of the exe-file-compile-logic. Next step will probably be to remove the exe-file-compile and only use mocks. But like to see that my other changes is not affecting the old tests before changing the tests also.

File: src/NLog/Config/LoggingConfigurationFileLoader.cs [hunk 8]
```diff
@@ -51,23 +52,23 @@ namespace NLog.Config
     /// </summary>
     internal class LoggingConfigurationFileLoader : ILoggingConfigurationLoader
     {
-        private static readonly FileWrapper DefaultFileWrapper = new FileWrapper();
-        private readonly IFile _file;
+        private static readonly AppEnvironmentWrapper DefaultFileWrapper = new AppEnvironmentWrapper();
```
Comment (304NotModified) [inline src/NLog/Config/LoggingConfigurationFileLoader.cs]: I think we should rename DefaultFileWrapper  here?

File: src/NLog/Config/LoggingConfigurationFileLoader.cs [hunk 9]
```diff
@@ -235,22 +252,84 @@ public IEnumerable<string> GetDefaultCandidateConfigFilePaths(string fileName)
...
+
+            foreach (var filePath in GetPrivateBinPathNLogLocations(baseDirectory, nlogConfigFile, platformFileSystemCaseInsensitive ? nLogConfigFileLowerCase : string.Empty))
+                yield return filePath;
+
+#if !SILVERLIGHT && !NETSTANDARD1_0
+            if (fileName == null)
+            {
+                // Get path to NLog.dll.nlog only if the assembly is not in the GAC
+                var nlogAssembly = typeof(LogFactory).GetAssembly();
+                if (!string.IsNullOrEmpty(nlogAssembly?.Location) && !nlogAssembly.GlobalAssemblyCache)
```
Comment (304NotModified) [inline src/NLog/Config/LoggingConfigurationFileLoader.cs]: Guess we should to do this one also (make mockable)

File: src/NLog/LayoutRenderers/ProcessIdLayoutRenderer.cs [hunk 10]
```diff
@@ -61,9 +63,9 @@ bool IRawValue.TryGetRawValue(LogEventInfo logEvent, out object value)
             return true;
         }
 
-        private static int GetValue()
+        private int GetValue()
         {
-            return ThreadIDHelper.Instance.CurrentProcessID;
+            return _currentProcessId != 0 ? _currentProcessId : (_currentProcessId = ProcessIDHelper.Instance.CurrentProcessID);
```
Comment (304NotModified) [inline src/NLog/LayoutRenderers/ProcessIdLayoutRenderer.cs]: just checking, this kind of a "cache"?

File: tests/NLog.UnitTests/ConfigFileLocatorTests.cs [hunk 11]
```diff
@@ -48,9 +45,234 @@ namespace NLog.UnitTests
...
+                EntryAssemblyFileName = "Entry.dll"
+            };
+
+            var fileLoader = new LoggingConfigurationFileLoader(appEnvMock);
+
+            // Act
+            var result = fileLoader.GetDefaultCandidateConfigFilePaths().ToList();
+
+            // Assert base-directory + process-directory + nlog-assembly-directory
+            if (NLog.Internal.PlatformDetector.IsWin32)
```
Comment (304NotModified) [inline tests/NLog.UnitTests/ConfigFileLocatorTests.cs]: please add some helpers for the test duplication (at least here in the assert part), thanks!

File: tests/NLog.UnitTests/Mocks/AppEnvironmentMock.cs [hunk 12]
```diff
@@ -32,23 +32,43 @@
...
 
 using System;
+using System.Collections.Generic;
+using System.Xml;
 using NLog.Internal.Fakeables;
 
 namespace NLog.UnitTests.Mocks
 {
-    public class FileMock : IFile
+    internal class AppEnvironmentMock : IAppEnvironment
```
Comment (304NotModified) [inline tests/NLog.UnitTests/Mocks/AppEnvironmentMock.cs]: FYI, you could  use NSubsitute  for this when #3274 is merged

File: src/NLog/Config/LoggingConfigurationFileLoader.cs (hunk 9 above)
Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: Think I have the code-coverage I need. For another time.

File: src/NLog/Config/LoggingConfigurationFileLoader.cs (hunk 8 above)
Comment (snakefoot) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: Good idea

File: src/NLog/Config/LoggingConfigurationFileLoader.cs (hunk 9 above)
Comment (304NotModified) [reply src/NLog/Config/LoggingConfigurationFileLoader.cs]: Fair enough

**Comment by 304NotModified** [comment]
maybe we should update the docs - and this unfortunately related: https://github.com/NLog/NLog/pull/959

File: src/NLog/LayoutRenderers/ProcessIdLayoutRenderer.cs (hunk 10 above)
Comment (snakefoot) [reply src/NLog/LayoutRenderers/ProcessIdLayoutRenderer.cs]: Yes but it is silly. Have remove it.

File: tests/NLog.UnitTests/ConfigFileLocatorTests.cs (hunk 11 above)
Comment (snakefoot) [reply tests/NLog.UnitTests/ConfigFileLocatorTests.cs]: Done

**Comment by snakefoot** [comment]
> @304NotModified  maybe we should update the docs

Well this PR actually tries to ensure that NetCore follows the Wiki :)

File: tests/NLog.UnitTests/Mocks/AppEnvironmentMock.cs (hunk 12 above)
Comment (snakefoot) [reply tests/NLog.UnitTests/Mocks/AppEnvironmentMock.cs]: Fine with implementing simple mocks by hand. It is more when meeting the monster-interface (or non-interfaces) that Mock-frameworks are helpful.

**Comment by 304NotModified** [comment]
so supersedes #959? Isn't this a breaking behavior change?

**Comment by snakefoot** [comment]
> @304NotModified so supersedes #959? Isn't this a breaking behavior change?

No and No.

#959 actually implements the config loading so it happens in the correct order. It should always use the application-specific process.exe.nlog instead of a random Nlog.config. But this is a breaking change, so you have stalled this fix for NLog 5.0

This PR only fixes NetCore so it behaves like NetFramework. Because `AppDomain.SetupInformation.ConfigurationFile` is blank on NetCore-platform and needs special help.

**Comment by 304NotModified** [comment]
Ok thanks for explaining!

FYI, I like to start with merging 5.0 PRs after 4.6.3 is done.

**Comment by snakefoot** [comment]
> FYI, I like to start with merging 5.0 PRs after 4.6.3 is done.

Think we should keep dev and master available for more hotfixes a few more weeks before starting up on NLog 5.0. But your decision.

**Comment by 304NotModified** [comment]
Hotfixes could be done to master then :)

(But features will be 5.0 instead of 4.6.*)

**Comment by snakefoot** [comment]
@304NotModified Is the merge of this PR blocked by something?

**Comment by 304NotModified** [comment]
Yes my time. I try to do some developing next to reviewing. Only reviewing is boring and I'm losing some touch to NLog in that way.

File: src/NLog/Config/XmlLoggingConfiguration.cs [hunk 13]
```diff
@@ -64,7 +64,7 @@ public class XmlLoggingConfiguration : LoggingConfigurationParser
         /// <summary>
         /// Prefix for assets in Xamarin Android
         /// </summary>
-        internal const string AssetsPrefix = "assets/";
+        private const string AssetsPrefix = "assets/";
```
Comment (304NotModified) [inline src/NLog/Config/XmlLoggingConfiguration.cs]: 👍

File: src/NLog/Internal/Fakeables/IFileSystem.cs [hunk 14]
```diff
@@ -33,14 +33,18 @@
...
 namespace NLog.Internal.Fakeables
 {
+    using System.Xml;
+
     /// <summary>
-    /// Abstract calls to File
+    /// Abstract calls to FileSystem
     /// </summary>
-    internal interface IFile
+    internal interface IFileSystem
```
Comment (304NotModified) [inline src/NLog/Internal/Fakeables/IFileSystem.cs]: FYI, this was not the direction I would take. I think it's better to have 10 small interfaces then 3 medium. 

Also, with the introduction of NSubstitute, really small interfaces are nice. 

But as it's internal I think this is more than good enough 👍

**Comment by 304NotModified** [comment]
> @304NotModified Is the merge of this PR blocked by something?

Anyway, pushing has some results ;)

**Comment by 304NotModified** [comment]
nice results!

image

**Comment by snakefoot** [comment]
> @304NotModified  Yes my free time. I try to do some developing next to reviewing. Only reviewing is boring and I'm losing some touch to NLog in that way.

Very understandable. I also prefer developing over reviewing :) Will try and reduce the number of PRs for the NLog-project, so everything is not about my PRs :)

But thank you for the merge. Now there is some cleanup to do:
- Refactor the remaining unit tests in `ConfigFileLocatorTests.cs` to use the new mock-interface instead of building exe-file (Faster and can be tested on NetCore).
- Update #959 to handle the moving of code from `LogFactory` to `LoggingConfigurationFileLoader`

I don't mind fixing these two, unless they should be up-for-grabs?
